-- Fills primary_muscle_group / movement_type / laterality for every
-- exercise currently in the library (the 965 bulk-imported names,
-- classified by the same movement-pattern system used for their
-- descriptions/cues in 0044, plus the 214 exercises from the real,
-- verified program content in 0004/0007/0008/0009/0014, hand-classified).
--
-- 'mobility' movement_type covers stretches, foam rolling, breathing, and
-- balance drills that aren't really compound or accessory strength work.
-- 'Balance/Mobility' muscle_group is the catch-all for those when no
-- single body part is the target (marching, ankle circles, sit-to-stand).
--
-- Only fills exercises missing this data, so it never overwrites anything
-- set by hand since (e.g. via the Library screen).
update public.exercises e
set
  primary_muscle_group = v.muscle_group,
  movement_type = v.movement_type,
  laterality = v.laterality
from (values
  ('Ab Wheel Kneeling Rollout', 'Core', 'accessory', 'bilateral'),
  ('Alternating Double Clubbell Pullover', 'Back', 'accessory', 'unilateral'),
  ('Alternating Double Dumbbell Bent Over Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Double Dumbbell Cyclist Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Alternating Double Dumbbell Incline Bench Prone Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Double Dumbbell Prone Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Double Dumbbell Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Alternating Double Kettlebell Bent Over Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Double Kettlebell Cyclist Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Alternating Double Kettlebell Incline Bench Prone Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Double Kettlebell Prone Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Single Arm Dumbbell Low Hold Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Alternating Single Arm Dumbbell Pendlay Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Single Arm Kettlebell Around the World', 'Core', 'accessory', 'bilateral'),
  ('Alternating Single Arm Kettlebell Low Hold Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Alternating Single Arm Kettlebell Outside Swing', 'Glutes', 'compound', 'unilateral'),
  ('Alternating Single Arm Kettlebell Pendlay Row', 'Back', 'compound', 'unilateral'),
  ('Alternating Single Arm Kettlebell Start Stop Swing', 'Glutes', 'compound', 'unilateral'),
  ('Alternating Single Arm Kettlebell Sumo Deadlift', 'Glutes', 'compound', 'bilateral'),
  ('Alternating Single Arm Tall Kneeling Around the World', 'Core', 'accessory', 'bilateral'),
  ('Bar Eccentric Pull Up', 'Back', 'compound', 'bilateral'),
  ('Barbell Back Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Barbell Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Barbell Block Pull Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Barbell Box Back Squat', 'Quads', 'compound', 'bilateral'),
  ('Barbell Conventional Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Barbell Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Barbell Front Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Barbell Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Barbell Halting Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Barbell High Bar Back Squat', 'Quads', 'compound', 'bilateral'),
  ('Barbell Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Barbell Inverted Row', 'Back', 'compound', 'bilateral'),
  ('Barbell Pendlay Row', 'Back', 'compound', 'bilateral'),
  ('Barbell Prone Row', 'Back', 'compound', 'bilateral'),
  ('Barbell Rack Pull', 'Back', 'compound', 'bilateral'),
  ('Barbell Reverse Grip Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Barbell Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Barbell Stiff Legged Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Barbell Sumo Back Squat', 'Glutes', 'compound', 'bilateral'),
  ('Barbell Sumo Deadlift', 'Glutes', 'compound', 'bilateral'),
  ('Battle Rope Alternating Side Slam', 'Core', 'compound', 'unilateral'),
  ('Battle Rope Power Slam', 'Full Body', 'compound', 'bilateral'),
  ('Battle Rope Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bodyweight Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Alternating Heel Taps', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Alternating Lateral Bench Jump', 'Full Body', 'compound', 'bilateral'),
  ('Bodyweight Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Bodyweight Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Alternating Single Leg V Up', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Alternating Single Leg Wall Sit', 'Quads', 'accessory', 'bilateral'),
  ('Bodyweight Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Bear Crawl', 'Core', 'compound', 'bilateral'),
  ('Bodyweight Bent Knee Copenhagen Plank', 'Adductors', 'accessory', 'unilateral'),
  ('Bodyweight Bent Knee Reverse Hyperextension', 'Hamstrings', 'accessory', 'bilateral'),
  ('Bodyweight Bent Knee Windshield Wiper', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Bicycle Crunch', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Bird Dog', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Bird Dog Knee to Elbow', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Box Pistol Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Bulgarian Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Butterfly Sit Up', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Copenhagen Plank', 'Adductors', 'accessory', 'unilateral'),
  ('Bodyweight Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bodyweight Crunch', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Extended Range Side Lying Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Bodyweight Face the Wall Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Feet Elevated Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Bodyweight Feet Elevated Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Bodyweight Feet Elevated Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Fire Hydrant', 'Glutes', 'accessory', 'unilateral'),
  ('Bodyweight Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bodyweight Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Forearm Plank', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Bodyweight Frog Reverse Hyperextension', 'Glutes', 'accessory', 'bilateral'),
  ('Bodyweight Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Bodyweight Glute Bridge Isometric with Alternating Single Leg Extension', 'Glutes', 'accessory', 'unilateral'),
  ('Bodyweight Hamstring Walkout', 'Hamstrings', 'compound', 'bilateral'),
  ('Bodyweight Hand Assisted Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Hand Assisted Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Hand Assisted Sissy Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Hand Assisted Skater Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Hand Assisted Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Bodyweight Hollow Body Flutter Kicks', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Hollow Body Hold', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight In and Out Squat Jump', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Isometric Split Squat Hold', 'Quads', 'accessory', 'unilateral'),
  ('Bodyweight Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Kneeling Forearm Plank', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Kneeling Side Plank', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Kneeling Side Plank Clamshell', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Lateral Bear Crawl', 'Core', 'compound', 'bilateral'),
  ('Bodyweight Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Bodyweight Low Switch Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bodyweight Mountain Climber', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Oblique Crunch', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Pivot Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Prone Cobra', 'Back', 'accessory', 'bilateral'),
  ('Bodyweight Quadruped Hip Extension', 'Glutes', 'accessory', 'unilateral'),
  ('Bodyweight Reverse Crunch', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Reverse Hyperextension', 'Hamstrings', 'accessory', 'bilateral'),
  ('Bodyweight Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Reverse Plank', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Seated Ab Circles', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Side Lying Clamshell', 'Glutes', 'accessory', 'unilateral'),
  ('Bodyweight Side Lying Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Bodyweight Side Lying Hip Adduction', 'Adductors', 'accessory', 'unilateral'),
  ('Bodyweight Side Plank', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Side Plank Reach Through', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Single Leg Foot Elevated Glute Bridge', 'Glutes', 'accessory', 'unilateral'),
  ('Bodyweight Single Leg Glute Bridge', 'Glutes', 'accessory', 'unilateral'),
  ('Bodyweight Single Leg Hip Thrust', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Sit Up', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Squat to Bench', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bodyweight Supine Alternating Single Leg Raise', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Supine Leg Raise', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Toe Balance Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Tuck Jump', 'Full Body', 'compound', 'bilateral'),
  ('Bodyweight V Up', 'Core', 'accessory', 'bilateral'),
  ('Bodyweight Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Bodyweight Wall Sit', 'Quads', 'accessory', 'bilateral'),
  ('Bodyweight Wall Slide Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Windmill', 'Core', 'accessory', 'unilateral'),
  ('Bodyweight Windshield Wiper', 'Core', 'accessory', 'bilateral'),
  ('Bulgarian Bag Back Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Bulgarian Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Bulgarian Bag Back Rack Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Low Switch Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Bulgarian Bag Back Rack Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Bulgarian Bag Back Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Bag Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Bulgarian Bag Swing', 'Glutes', 'compound', 'bilateral'),
  ('Bulgarian Bag Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Cable Fire Hydrant', 'Glutes', 'accessory', 'unilateral'),
  ('Cable Glute Kickback', 'Glutes', 'accessory', 'unilateral'),
  ('Cable Half Kneeling Pallof Press', 'Core', 'accessory', 'unilateral'),
  ('Cable Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Cable Hip Adduction', 'Adductors', 'accessory', 'unilateral'),
  ('Cable Hip Rotation', 'Glutes', 'accessory', 'unilateral'),
  ('Cable Kneeling Crunch', 'Core', 'accessory', 'bilateral'),
  ('Cable Pallof Press', 'Core', 'accessory', 'unilateral'),
  ('Cable Prone Bench Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Cable Prone Bench Single Leg Hamstring Curl', 'Hamstrings', 'accessory', 'unilateral'),
  ('Cable Prone Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Cable Prone Single Leg Hamstring Curl', 'Hamstrings', 'accessory', 'unilateral'),
  ('Cable Pull Through', 'Glutes', 'compound', 'bilateral'),
  ('Cable Quadruped Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Cable Reverse Crunch', 'Core', 'accessory', 'bilateral'),
  ('Cable Reverse Grip Lat Pulldown', 'Back', 'compound', 'bilateral'),
  ('Cable Rope Pullover', 'Back', 'accessory', 'bilateral'),
  ('Cable Seated Crunch', 'Core', 'accessory', 'bilateral'),
  ('Cable Single Leg Standing Bent Knee Hip External Rotation', 'Glutes', 'accessory', 'unilateral'),
  ('Cable Standing Single Leg Hamstring Curl', 'Hamstrings', 'accessory', 'unilateral'),
  ('Cable Straight Bar Pullover', 'Back', 'accessory', 'bilateral'),
  ('Cable Tall Kneeling Pallof Press', 'Core', 'accessory', 'unilateral'),
  ('Cable Tall Kneeling Pull Through', 'Glutes', 'compound', 'bilateral'),
  ('Cable V Grip Lat Pulldown', 'Back', 'compound', 'bilateral'),
  ('Cable V Grip Seated Floor Lat Pulldown', 'Back', 'compound', 'bilateral'),
  ('Cable V Grip Seated Low Row', 'Back', 'accessory', 'bilateral'),
  ('Cable Wide Grip Lat Pulldown', 'Back', 'compound', 'bilateral'),
  ('Clubbell Barbarian Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Barbarian Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Barbarian Squat', 'Quads', 'compound', 'bilateral'),
  ('Clubbell Clean', 'Full Body', 'compound', 'bilateral'),
  ('Clubbell Order Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Clubbell Order Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Order Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Clubbell Order Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Clubbell Order Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Clubbell Order Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Order Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Order Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Order Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Clubbell Order Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Order Squat', 'Quads', 'compound', 'bilateral'),
  ('Clubbell Order Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Clubbell Order Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Clubbell Pullover', 'Back', 'accessory', 'bilateral'),
  ('Clubbell Shoulder Park Squat', 'Quads', 'compound', 'bilateral'),
  ('Clubbell Swing', 'Glutes', 'compound', 'bilateral'),
  ('Double Clubbell Barbarian Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Clubbell Clean', 'Full Body', 'compound', 'bilateral'),
  ('Double Clubbell Order Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Clubbell Order Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Clubbell Order Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Clubbell Order Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Clubbell Order Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Clubbell Order Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Clubbell Order Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Clubbell Order Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Clubbell Order Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Clubbell Order Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Clubbell Order Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Clubbell Order Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Clubbell Pullover', 'Back', 'accessory', 'bilateral'),
  ('Double Dumbbell Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Double Dumbbell Cyclist Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Double Dumbbell Front Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Carry', 'Full Body', 'compound', 'bilateral'),
  ('Double Dumbbell Front Rack Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Dumbbell Front Rack Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Dumbbell Front Rack Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Front Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Incline Bench Prone Row', 'Back', 'compound', 'bilateral'),
  ('Double Dumbbell Low Hold Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Low Hold Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Low Hold Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Low Hold Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Pendlay Row', 'Back', 'compound', 'bilateral'),
  ('Double Dumbbell Prone Row', 'Back', 'compound', 'bilateral'),
  ('Double Dumbbell Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Double Dumbbell Seated Good Morning', 'Hamstrings', 'accessory', 'bilateral'),
  ('Double Dumbbell Seesaw Bent Over Row', 'Back', 'compound', 'unilateral'),
  ('Double Dumbbell Staggered Stance Romanian Deadlift', 'Hamstrings', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Dumbbell Suitcase Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Double Dumbbell Suitcase Deficit Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Dumbbell Suitcase Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Dumbbell Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Double Kettlebell Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Double Kettlebell Cyclist Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Double Kettlebell Front Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Carry', 'Full Body', 'compound', 'bilateral'),
  ('Double Kettlebell Front Rack Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Kettlebell Front Rack Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Kettlebell Front Rack Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Front Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Gorilla Row', 'Back', 'compound', 'unilateral'),
  ('Double Kettlebell Incline Bench Prone Row', 'Back', 'compound', 'bilateral'),
  ('Double Kettlebell Low Hold Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Low Hold Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Mountain Climber', 'Core', 'accessory', 'bilateral'),
  ('Double Kettlebell Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Double Kettlebell Outside Swing', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Pendlay Row', 'Back', 'compound', 'bilateral'),
  ('Double Kettlebell Prone Row', 'Back', 'compound', 'bilateral'),
  ('Double Kettlebell Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Double Kettlebell Seesaw Bent Over Row', 'Back', 'compound', 'unilateral'),
  ('Double Kettlebell Start Stop Swing', 'Glutes', 'compound', 'bilateral'),
  ('Double Kettlebell Suitcase Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Double Kettlebell Suitcase Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Double Kettlebell Suitcase Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Double Kettlebell Suitcase Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Double Kettlebell Sumo Deadlift', 'Glutes', 'compound', 'bilateral'),
  ('Double Kettlebell Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Dumbbell Crush Grip Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Dumbbell Crush Grip Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Dumbbell Crush Grip Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Dumbbell Crush Grip Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Dumbbell Crush Grip Seated Good Morning', 'Hamstrings', 'accessory', 'bilateral'),
  ('Dumbbell Feet Elevated Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Dumbbell Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Dumbbell Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Dumbbell Goblet Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Dumbbell Goblet Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Dumbbell Goblet Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Dumbbell Goblet Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Carry', 'Full Body', 'compound', 'bilateral'),
  ('Dumbbell Goblet Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Dumbbell Goblet Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Dumbbell Goblet Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Dumbbell Goblet Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Dumbbell Goblet Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Dumbbell Goblet Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Dumbbell Goblet Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Dumbbell Goblet Squat', 'Quads', 'compound', 'bilateral'),
  ('Dumbbell Goblet Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Dumbbell Goblet Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Dumbbell Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Dumbbell Incline Bench Pullover', 'Back', 'accessory', 'bilateral'),
  ('Dumbbell Low Hold Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Dumbbell Low Hold Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Dumbbell Pullover', 'Back', 'accessory', 'bilateral'),
  ('Dumbbell Single Leg Romanian Dedlift', 'Hamstrings', 'compound', 'bilateral'),
  ('EZ Bar Reverse Grip Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Kettlebell Bottoms Up Horn Grip Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Kettlebell Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Kettlebell Feet Elevated Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Kettlebell Feet Elevated Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Kettlebell Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Kettlebell Goblet Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Goblet Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Goblet Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Goblet Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Carry', 'Full Body', 'compound', 'bilateral'),
  ('Kettlebell Goblet Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Goblet Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Kettlebell Goblet Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Goblet Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Goblet Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Goblet Horse Stance Squat', 'Adductors', 'compound', 'bilateral'),
  ('Kettlebell Goblet Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Goblet Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Goblet Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Goblet Squat', 'Quads', 'compound', 'bilateral'),
  ('Kettlebell Goblet Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Goblet Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Carry', 'Full Body', 'compound', 'bilateral'),
  ('Kettlebell Horn Grip Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Kettlebell Horn Grip Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Squat', 'Quads', 'compound', 'bilateral'),
  ('Kettlebell Horn Grip Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Kettlebell Horn Grip Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Kettlebell Low Hold Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Low Hold Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Low Hold Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Low Hold Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Kettlebell Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Kettlebell Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Kettlebell Start Stop Swing', 'Glutes', 'compound', 'bilateral'),
  ('Kettlebell Sumo Deadlift', 'Glutes', 'compound', 'bilateral'),
  ('Kettlebell Swing', 'Glutes', 'compound', 'bilateral'),
  ('Landmine Goblet Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Landmine Goblet Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Landmine Goblet Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Landmine Goblet Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Landmine Goblet Squat', 'Quads', 'compound', 'bilateral'),
  ('Landmine Low Hold Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Landmine Low Hold Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Landmine Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Landmine Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Landmine Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Landmine V Grip Row', 'Back', 'compound', 'bilateral'),
  ('Macebell Barbarian Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Macebell Barbarian Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Macebell Barbarian Squat', 'Quads', 'compound', 'bilateral'),
  ('Macebell Offset Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Macebell Order Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Macebell Order Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Macebell Order Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Macebell Order Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Macebell Order Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Macebell Order Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Macebell Order Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Macebell Order Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Macebell Order Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Macebell Order Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Macebell Order Squat', 'Quads', 'compound', 'bilateral'),
  ('Macebell Order Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Macebell Order Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Macebell Reverse Grip Offset Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Medicine Ball Alternating Single Leg V Up', 'Core', 'accessory', 'unilateral'),
  ('Medicine Ball Feet Elevated Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Medicine Ball Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Medicine Ball Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Medicine Ball V Up', 'Core', 'accessory', 'bilateral'),
  ('Miniband 3 Way Cha Cha', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Ankle Lateral Walk', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Ankle Monster Walk', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Ankle Side Lying Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Miniband Bench Seated Hip Abduction', 'Abductors', 'accessory', 'bilateral'),
  ('Miniband Bicycle Crunch', 'Core', 'accessory', 'bilateral'),
  ('Miniband Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Miniband Feet Elevated Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Feet Elevated Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Fire Hydrant', 'Glutes', 'accessory', 'unilateral'),
  ('Miniband Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Glute Bridge Hip Abduction', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Miniband Kneeling Side Plank Clamshell', 'Core', 'accessory', 'unilateral'),
  ('Miniband Quadruped Hip Extension', 'Glutes', 'accessory', 'unilateral'),
  ('Miniband Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Miniband Side Lying Clamshell', 'Glutes', 'accessory', 'unilateral'),
  ('Miniband Single Leg Hip Thrust', 'Glutes', 'compound', 'unilateral'),
  ('Miniband Standing Glute Kickback', 'Glutes', 'accessory', 'unilateral'),
  ('Miniband Standing Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Miniband Thigh In and Out Squat Jump', 'Quads', 'compound', 'bilateral'),
  ('Miniband Thigh Kneeling Side Plank Hip Abduction', 'Core', 'accessory', 'unilateral'),
  ('Miniband Thigh Lateral Walk', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Thigh Monster Walk', 'Glutes', 'accessory', 'bilateral'),
  ('Miniband Thigh Side Plank Hip Abduction', 'Core', 'accessory', 'unilateral'),
  ('Miniband Wall Sit Hip Abduction', 'Quads', 'accessory', 'bilateral'),
  ('Parallette Mountain Climber', 'Core', 'accessory', 'bilateral'),
  ('Parallette Plank', 'Core', 'accessory', 'bilateral'),
  ('Plate Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Plate Feet Elevated Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Plate Feet Elevated Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Plate Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Plate Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Plate Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Plate Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Plate Side Lying Bent Knee Hip Abduction', 'Abductors', 'accessory', 'unilateral'),
  ('Resistance Band Low Row', 'Back', 'accessory', 'bilateral'),
  ('Resistance Band Mid Row', 'Back', 'accessory', 'bilateral'),
  ('Ring Body Saw', 'Core', 'accessory', 'bilateral'),
  ('Ring Bulgarian Row', 'Back', 'compound', 'bilateral'),
  ('Ring Eccentric Pull Up', 'Back', 'compound', 'bilateral'),
  ('Ring Plank', 'Core', 'accessory', 'bilateral'),
  ('Ring Row', 'Back', 'compound', 'bilateral'),
  ('Sandbag Back Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Back Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Back Rack Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Back Rack Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Back Rack Bulgarian Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Back Rack Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Back Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Back Rack Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Back Rack Low Switch Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Back Rack Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Back Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Back Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Sandbag Back Rack Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Back Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Sandbag Front Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Front Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Front Rack Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Front Rack Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Bulgarian Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Front Rack Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Front Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Sandbag Front Rack Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Front Rack Foot Elevated Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Front Rack Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Front Rack Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Front Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Front Rack Low Switch Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Sandbag Front Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Sandbag Front Rack Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Sandbag Front Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Sandbag Thruster', 'Full Body', 'compound', 'bilateral'),
  ('Single Arm Barbell Suitcase Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Single Arm Cable Half Kneeling Lat Pulldown', 'Back', 'compound', 'unilateral'),
  ('Single Arm Cable Half Kneeling Low Row', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Cable Seated Floor Lat Pulldown', 'Back', 'compound', 'unilateral'),
  ('Single Arm Cable Shotgun Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Clubbell Barbarian Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Clubbell Clean', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Clubbell Inside Pullover', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Clubbell Order Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Contralateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Foot Elevated Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Foot Elevated Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Ipsilateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Clubbell Order Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Clubbell Order Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Clubbell Outside Pullover', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Clubbell Pullover', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Clubbell Shoulder Park Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Dumbbell Bent Over Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Cyclist Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Carry', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Contralateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Dumbbell Front Rack Foot Elevated Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Foot Elevated Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Dumbbell Front Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Incline Bench Prone Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Knee Supported Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Pendlay Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Contralateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Dumbbell Suitcase Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Single Arm Dumbbell Suitcase Foot Elevated Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Foot Elevated Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Suitcase Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Dumbbell Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Around the World', 'Core', 'accessory', 'bilateral'),
  ('Single Arm Kettlebell Bent Over Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Cyclist Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Carry', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Contralateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Kettlebell Front Rack Foot Elevated Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Foot Elevated Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Front Rack Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Kettlebell Front Rack Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Incline Bench Prone Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Knee Supported Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Outside Swing', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Pendlay Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Prone Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Rotational Thruster', 'Full Body', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Start Stop Swing', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Contralateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Kettlebell Suitcase Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Single Arm Kettlebell Suitcase Foot Elevated Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Foot Elevated Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Suitcase Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Sumo Deadlift', 'Glutes', 'compound', 'bilateral'),
  ('Single Arm Kettlebell Swing', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Kettlebell Tall Kneeling Around the World', 'Core', 'accessory', 'bilateral'),
  ('Single Arm Landmine Front Rack Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Landmine Front Rack Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Landmine Meadows Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Landmine Row', 'Back', 'compound', 'unilateral'),
  ('Single Arm Landmine Suitcase Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Alternating Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Contralateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Macebell Order Foot Elevated Contralateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Foot Elevated Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Forward Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Knee Over Toe Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Ipsilateral Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Single Arm Macebell Order Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Macebell Order Walking Lunge', 'Quads', 'compound', 'unilateral'),
  ('Single Arm Resistance Band Low Row', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Resistance Band Mid Row', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Suspension Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Suspension Contralateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Suspension Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Single Arm Suspension Foot Elevated Contralateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Suspension Foot Elevated Ipsilateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Suspension Ipsilateral Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Suspension Low Row', 'Back', 'accessory', 'unilateral'),
  ('Single Arm Suspension Low Switch Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Single Arm Suspension Mid Row', 'Back', 'accessory', 'unilateral'),
  ('Slam Ball Otis Up', 'Full Body', 'compound', 'unilateral'),
  ('Slam Ball Overhead Slam', 'Full Body', 'compound', 'bilateral'),
  ('Slam Ball Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Slam Ball Tall Kneeling Overhead Slam', 'Full Body', 'compound', 'bilateral'),
  ('Slider Body Saw', 'Core', 'accessory', 'bilateral'),
  ('Slider Bulgarian Bag Back Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Bulgarian Bag Back Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Bulgarian Bag Back Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Clubbell Order Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Clubbell Order Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Clubbell Order Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Clubbell Order Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Clubbell Order Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Double Clubbell Order Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Dumbbell Front Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Dumbbell Front Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Double Dumbbell Front Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Dumbbell Suitcase Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Dumbbell Suitcase Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Double Dumbbell Suitcase Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Kettlebell Front Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Kettlebell Front Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Double Kettlebell Front Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Kettlebell Suitcase Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Double Kettlebell Suitcase Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Double Kettlebell Suitcase Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Dumbbell Goblet Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Dumbbell Goblet Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Dumbbell Goblet Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Eccentric Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Slider Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Slider Kettlebell Goblet Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Kettlebell Goblet Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Kettlebell Goblet Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Kettlebell Horn Grip Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Kettlebell Horn Grip Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Kettlebell Horn Grip Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Knee Tuck', 'Core', 'accessory', 'bilateral'),
  ('Slider Landmine Goblet Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Landmine Goblet Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Landmine Low Hold Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Macebell Order Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Macebell Order Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Macebell Order Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Mountain Climber', 'Core', 'accessory', 'bilateral'),
  ('Slider Parallette Knee Tuck', 'Core', 'accessory', 'bilateral'),
  ('Slider Parallette Mountain Climber', 'Core', 'accessory', 'bilateral'),
  ('Slider Plank Jack', 'Core', 'accessory', 'bilateral'),
  ('Slider Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Sandbag Back Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Sandbag Back Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Sandbag Back Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Sandbag Front Rack Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Sandbag Front Rack Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Sandbag Front Rack Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Clubbell Order Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Clubbell Order Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Clubbell Order Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Clubbell Order Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Clubbell Order Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Clubbell Order Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Front Rack Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Front Rack Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Front Rack Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Low Hold Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Suitcase Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Suitcase Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Suitcase Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Dumbbell Suitcase Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Low Hold Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Suitcase Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Suitcase Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Suitcase Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Landmine Front Rack Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Landmine Front Rack Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Landmine Suitcase Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Landmine Suitcase Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Macebell Order Contralateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Macebell Order Contralateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Macebell Order Contralateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Macebell Order Ipsilateral Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Single Arm Macebell Order Ipsilateral Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Single Arm Macebell Order Ipsilateral Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Suspension Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Slider Suspension Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Slider Suspension Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Stability Ball Bent Knee Reverse Hyperextension', 'Hamstrings', 'accessory', 'bilateral'),
  ('Stability Ball Body Saw', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Cable Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Crunch', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Stability Ball Dumbbell Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Stability Ball Dumbbell Pullover', 'Back', 'accessory', 'bilateral'),
  ('Stability Ball Feet Elevated Crunch', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Feet Elevated Frog Pump', 'Glutes', 'accessory', 'bilateral'),
  ('Stability Ball Feet Elevated Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Stability Ball Feet Elevated Oblique Crunch', 'Core', 'accessory', 'unilateral'),
  ('Stability Ball Feet Elevated Plank', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Feet Elevated Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Forearm Plank', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Frog Reverse Hyperextension', 'Glutes', 'accessory', 'bilateral'),
  ('Stability Ball Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Stability Ball Hip Thrust', 'Glutes', 'compound', 'bilateral'),
  ('Stability Ball Hyperextension', 'Hamstrings', 'accessory', 'bilateral'),
  ('Stability Ball Knee Tuck', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Kneeling Body Saw', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Kneeling Rollout', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Kneeling Stir the Pot', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Miniband Feet Elevated Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Stability Ball Oblique Crunch', 'Core', 'accessory', 'unilateral'),
  ('Stability Ball Prone Cobra', 'Back', 'accessory', 'bilateral'),
  ('Stability Ball Reverse Crunch', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Reverse Hyperextension', 'Hamstrings', 'accessory', 'bilateral'),
  ('Stability Ball Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Single Leg Hip Thrust', 'Glutes', 'compound', 'unilateral'),
  ('Stability Ball Sit Up', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Stir the Pot', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball V Up Pass', 'Core', 'accessory', 'bilateral'),
  ('Stability Ball Wall Slide Squat', 'Quads', 'compound', 'bilateral'),
  ('Stability Ball Windshield Wiper', 'Core', 'accessory', 'bilateral'),
  ('Superband Assisted Bar Pull Up', 'Back', 'compound', 'bilateral'),
  ('Superband Assisted Reverse Nordic', 'Quads', 'accessory', 'bilateral'),
  ('Superband Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Superband Good Morning', 'Hamstrings', 'compound', 'bilateral'),
  ('Superband Half Kneeling Pallof Press', 'Core', 'accessory', 'unilateral'),
  ('Superband Lateral Step Hip Adduction', 'Adductors', 'accessory', 'unilateral'),
  ('Superband Pallof Press', 'Core', 'accessory', 'unilateral'),
  ('Superband Prone Bench Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Superband Prone Bench Single Leg Hamstring Curl', 'Hamstrings', 'accessory', 'unilateral'),
  ('Superband Prone Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Superband Prone Single Leg Hamstring Curl', 'Hamstrings', 'accessory', 'unilateral'),
  ('Superband Pull Through', 'Glutes', 'compound', 'bilateral'),
  ('Superband Side Lying Hanging Hip Adduction', 'Adductors', 'accessory', 'bilateral'),
  ('Superband Single Leg Standing Bent Knee Hip External Rotation', 'Glutes', 'accessory', 'unilateral'),
  ('Superband Standing Hip Adduction', 'Adductors', 'accessory', 'unilateral'),
  ('Superband Tall Kneeling Pallof Press', 'Core', 'accessory', 'unilateral'),
  ('Superband Tall Kneeling Pull Through', 'Glutes', 'compound', 'bilateral'),
  ('Suspension Alternating Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Suspension Alternating Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Suspension Alternating Lateral Lunge', 'Adductors', 'compound', 'unilateral'),
  ('Suspension Alternating Reverse Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Suspension Body Saw', 'Core', 'accessory', 'bilateral'),
  ('Suspension Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Suspension Curtsy Lunge', 'Glutes', 'compound', 'unilateral'),
  ('Suspension Cyclist Squat', 'Quads', 'compound', 'bilateral'),
  ('Suspension Feet Elevated Forearm Plank', 'Core', 'accessory', 'bilateral'),
  ('Suspension Feet Elevated Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Suspension Feet Elevated Plank', 'Core', 'accessory', 'bilateral'),
  ('Suspension Foot Elevated Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Suspension Hamstring Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Suspension Knee Tuck', 'Core', 'accessory', 'bilateral'),
  ('Suspension Low Row', 'Back', 'accessory', 'bilateral'),
  ('Suspension Low Switch Cossack Squat', 'Adductors', 'compound', 'unilateral'),
  ('Suspension Mid Row', 'Back', 'accessory', 'bilateral'),
  ('Suspension Sissy Squat', 'Quads', 'compound', 'bilateral'),
  ('Suspension Skater Squat', 'Quads', 'compound', 'unilateral'),
  ('Suspension Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Suspension Squat', 'Quads', 'compound', 'bilateral'),
  ('Tire Alternating Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Tire Alternating Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Tire Bulgarian Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Tire Feet Elevated Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Tire Macebell Staggered Stance Slam', 'Full Body', 'compound', 'unilateral'),
  ('Tire Mountain Climber', 'Core', 'accessory', 'bilateral'),
  ('Tire Russian Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Tire Sledge Hammer Staggered Stance Slam', 'Full Body', 'compound', 'unilateral'),
  ('Tire Step Up', 'Glutes', 'compound', 'unilateral'),
  ('Trap Bar Bent Over Row', 'Back', 'compound', 'bilateral'),
  ('Trap Bar Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Trap Bar Pendlay Row', 'Back', 'compound', 'bilateral'),
  ('Trap Bar Rack Pull', 'Back', 'compound', 'bilateral'),
  ('Trap Bar Romanian Deadlift', 'Hamstrings', 'compound', 'bilateral'),
  ('Trap Bar Staggered Stance Deadlift', 'Hamstrings', 'compound', 'unilateral'),
  ('Wall Ball Body Saw', 'Core', 'accessory', 'bilateral'),
  ('Wall Ball Feet Elevated Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Wall Ball Half Kneeling Lateral Toss', 'Core', 'compound', 'unilateral'),
  ('Wall Ball Lateral Toss', 'Core', 'compound', 'unilateral'),
  ('Wall Ball Russian Twist', 'Core', 'accessory', 'bilateral'),
  ('Wall Ball Russian Twist Lateral Toss', 'Core', 'accessory', 'bilateral'),
  ('Ab/Core: Ball Slams -- AMRAP 30 sec', 'Core', 'compound', 'bilateral'),
  ('Ab/Core: Bird Dog (pain-free range)', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Bird Dog + Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Bird Dog to Elbow-Knee + Glute Bridge March', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Dead Bug (DB) + Leg Raise', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Dead Bug (pain-free range)', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Dead Bug + 90/90 Breathing', 'Core', 'accessory', 'bilateral'),
  ('Ab/Core: Dead Bug with Light DB', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Overhead Carry + KB Swings 3x10', 'Full Body', 'compound', 'bilateral'),
  ('Ab/Core: Pallof Press + 90/90 Breathing', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Pallof Press + Bird Dog with Reach', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Seated Marching + Bird Dog', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Seated Trunk Rotation + Bird Dog', 'Core', 'accessory', 'unilateral'),
  ('Ab/Core: Standing Marching + Trunk Rotation (standing)', 'Core', 'accessory', 'bilateral'),
  ('Ab/Core: Suitcase Carry (heavier)', 'Full Body', 'compound', 'bilateral'),
  ('Ab/Core: Suitcase Carry + Pallof Press', 'Full Body', 'compound', 'bilateral'),
  ('Ab/Core: Supine 90/90 Breathing', 'Core', 'mobility', 'bilateral'),
  ('Ab/Core: Walking Lunge -- laps down & back', 'Quads', 'compound', 'unilateral'),
  ('Ankle Pumps + Circles', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Heel-to-Toe Walk (near wall for safety)', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Heel-to-Toe Walk, added challenge', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Standing Ankle Circles + Toe Raises', 'Calves', 'mobility', 'bilateral'),
  ('Standing Ankle Raises', 'Calves', 'accessory', 'bilateral'),
  ('Standing Hip Circles', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Standing Hip Circles, added range', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Toe Raises, balance-focused', 'Calves', 'accessory', 'bilateral'),
  ('Marching in Place, faster tempo', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Marching in Place, holding counter', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Marching with High-Knee Reach', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Standing Marching, controlled', 'Balance/Mobility', 'mobility', 'bilateral'),
  ('Single-Leg Balance Reach', 'Balance/Mobility', 'accessory', 'unilateral'),
  ('Single-Leg Stance with Reach', 'Balance/Mobility', 'accessory', 'unilateral'),
  ('Single-Leg Stance, holding counter', 'Balance/Mobility', 'accessory', 'unilateral'),
  ('Side-Stepping, added resistance band', 'Abductors', 'accessory', 'bilateral'),
  ('Side-Stepping, hand-rail support', 'Abductors', 'accessory', 'bilateral'),
  ('Side-Stepping, longer distance', 'Abductors', 'accessory', 'bilateral'),
  ('Banded Lateral Walk + Pulse', 'Abductors', 'accessory', 'bilateral'),
  ('Back Squat', 'Quads', 'compound', 'bilateral'),
  ('Bodyweight Squat to Chair', 'Quads', 'compound', 'bilateral'),
  ('Goblet Squat', 'Quads', 'compound', 'bilateral'),
  ('Goblet Squat (deepest controlled range)', 'Quads', 'compound', 'bilateral'),
  ('Goblet Squat (higher rep)', 'Quads', 'compound', 'bilateral'),
  ('Goblet Squat to Chair (light DB)', 'Quads', 'compound', 'bilateral'),
  ('Goblet Squat to Depth', 'Quads', 'compound', 'bilateral'),
  ('Jump Squat', 'Quads', 'compound', 'bilateral'),
  ('Sumo Squat / Front Squat', 'Glutes', 'compound', 'bilateral'),
  ('Supported Squat (chair-assisted, partial range)', 'Quads', 'compound', 'bilateral'),
  ('Isometric Wall Sit (short hold, pain-free range)', 'Quads', 'mobility', 'bilateral'),
  ('Bulgarian Split Squat (loaded)', 'Quads', 'compound', 'unilateral'),
  ('Bulgarian Split Squat Jump', 'Quads', 'compound', 'unilateral'),
  ('Split Squat', 'Quads', 'compound', 'unilateral'),
  ('Split Squat (loaded)', 'Quads', 'compound', 'unilateral'),
  ('Multi-Planar Lunge, controlled', 'Quads', 'compound', 'unilateral'),
  ('Reverse Lunge w/ Lift', 'Glutes', 'compound', 'unilateral'),
  ('Walking Lunge (loaded)', 'Quads', 'compound', 'unilateral'),
  ('Walking Lunge (loaded, controlled)', 'Quads', 'compound', 'unilateral'),
  ('Lateral Step, controlled', 'Abductors', 'compound', 'unilateral'),
  ('Lateral Step-Up', 'Glutes', 'compound', 'unilateral'),
  ('Side Step-Up w/ Balance', 'Glutes', 'compound', 'unilateral'),
  ('Step-Down, controlled', 'Quads', 'compound', 'unilateral'),
  ('Step-Up (moderate ht., DB)', 'Glutes', 'compound', 'unilateral'),
  ('Step-Up w/ Lift', 'Glutes', 'compound', 'unilateral'),
  ('Step-Up w/ Lift (loaded)', 'Glutes', 'compound', 'unilateral'),
  ('Step-Up, real stair height', 'Glutes', 'compound', 'unilateral'),
  ('Single-Leg Box Step-Down (deceleration)', 'Quads', 'compound', 'unilateral'),
  ('Box Jump', 'Quads', 'compound', 'bilateral'),
  ('Broad Jump', 'Full Body', 'compound', 'bilateral'),
  ('Lateral Bound', 'Abductors', 'compound', 'unilateral'),
  ('Skater Hops', 'Abductors', 'compound', 'unilateral'),
  ('Hip Hinge Pattern (bodyweight RDL)', 'Hamstrings', 'compound', 'bilateral'),
  ('Hip Hinge Pattern (light DB RDL)', 'Hamstrings', 'compound', 'bilateral'),
  ('Hip Hinge to RDL (moderate DB)', 'Hamstrings', 'compound', 'bilateral'),
  ('Standing Hip Hinge, light', 'Hamstrings', 'compound', 'bilateral'),
  ('Standing Hip Hinge, light DB', 'Hamstrings', 'compound', 'bilateral'),
  ('Single-Leg Hip Hinge, controlled', 'Hamstrings', 'compound', 'unilateral'),
  ('Single-Leg RDL (loaded)', 'Hamstrings', 'compound', 'unilateral'),
  ('Single-Leg RDL to Hop', 'Hamstrings', 'compound', 'unilateral'),
  ('Single-Leg Reach', 'Hamstrings', 'accessory', 'unilateral'),
  ('Single-Leg Reach (loaded)', 'Hamstrings', 'accessory', 'unilateral'),
  ('Hip Thrust (barbell)', 'Glutes', 'compound', 'bilateral'),
  ('Hip Thrust (explosive up)', 'Glutes', 'compound', 'bilateral'),
  ('Hip Thrust (heaviest controlled load)', 'Glutes', 'compound', 'bilateral'),
  ('Hip Thrust (heaviest load)', 'Glutes', 'compound', 'bilateral'),
  ('Hip Thrust (higher volume)', 'Glutes', 'compound', 'bilateral'),
  ('Single-Leg Hip Thrust (loaded)', 'Glutes', 'compound', 'unilateral'),
  ('Glute Bridge (bodyweight, partial range)', 'Glutes', 'accessory', 'bilateral'),
  ('Glute Bridge March', 'Glutes', 'accessory', 'bilateral'),
  ('Glute Bridge, slow controlled', 'Glutes', 'accessory', 'bilateral'),
  ('Single-Leg Glute Bridge, controlled', 'Glutes', 'accessory', 'unilateral'),
  ('Banded Glute Bridge', 'Glutes', 'accessory', 'bilateral'),
  ('Banded Glute Bridge (higher rep)', 'Glutes', 'accessory', 'bilateral'),
  ('DB Row', 'Back', 'compound', 'bilateral'),
  ('Single-Arm DB Row', 'Back', 'compound', 'unilateral'),
  ('Single-Arm Row', 'Back', 'compound', 'unilateral'),
  ('Single-Arm Row (heavier)', 'Back', 'compound', 'unilateral'),
  ('Seated Cable Row', 'Back', 'compound', 'bilateral'),
  ('Seated Row (band)', 'Back', 'accessory', 'bilateral'),
  ('Seated Row (machine)', 'Back', 'compound', 'bilateral'),
  ('Seated Row (moderate load)', 'Back', 'compound', 'bilateral'),
  ('Seated Row, heavier band', 'Back', 'accessory', 'bilateral'),
  ('Standing Row to Overhead Carry', 'Back', 'compound', 'bilateral'),
  ('Standing Row to Overhead Reach', 'Back', 'compound', 'bilateral'),
  ('Standing Row to Overhead Reach (light DB)', 'Back', 'compound', 'bilateral'),
  ('Standing Row to Overhead Reach (moderate DB)', 'Back', 'compound', 'bilateral'),
  ('Standing Row, balance challenge', 'Back', 'compound', 'bilateral'),
  ('Standing Push with Band', 'Chest', 'accessory', 'bilateral'),
  ('Lat Pulldown (machine)', 'Back', 'compound', 'bilateral'),
  ('Pull-Up / Row (explosive)', 'Back', 'compound', 'bilateral'),
  ('Band Pull-Apart', 'Shoulders', 'accessory', 'bilateral'),
  ('Band Pull-Apart (heavier band)', 'Shoulders', 'accessory', 'bilateral'),
  ('Band Pull-Apart (higher volume)', 'Shoulders', 'accessory', 'bilateral'),
  ('Band Pull-Apart + External Rotation', 'Shoulders', 'accessory', 'bilateral'),
  ('Face Pull (cable)', 'Shoulders', 'accessory', 'bilateral'),
  ('Face Pull (heavier band)', 'Shoulders', 'accessory', 'bilateral'),
  ('Scapular Retraction (band, light)', 'Back', 'accessory', 'bilateral'),
  ('Wall Slide / Scapular Retraction', 'Shoulders', 'mobility', 'bilateral'),
  ('Wall Slide w/ Band', 'Shoulders', 'mobility', 'bilateral'),
  ('Wall Slide w/ Band (higher rep)', 'Shoulders', 'mobility', 'bilateral'),
  ('Single-Arm Wall Slide', 'Shoulders', 'mobility', 'unilateral'),
  ('Ball Flye', 'Chest', 'accessory', 'bilateral'),
  ('Ball Flye (heavier)', 'Chest', 'accessory', 'bilateral'),
  ('Cable Fly (machine)', 'Chest', 'accessory', 'bilateral'),
  ('DB Fly', 'Chest', 'accessory', 'bilateral'),
  ('Bench Press (moderate load)', 'Chest', 'compound', 'bilateral'),
  ('Chest Press (machine)', 'Chest', 'compound', 'bilateral'),
  ('DB Chest Press', 'Chest', 'compound', 'bilateral'),
  ('Incline DB/Barbell Press', 'Chest', 'compound', 'bilateral'),
  ('Incline Push-Up, more challenge', 'Chest', 'compound', 'bilateral'),
  ('Wall Push-Up', 'Chest', 'compound', 'bilateral'),
  ('Jump Push-Up / Explosive Press', 'Chest', 'compound', 'bilateral'),
  ('Plyo Push-Up', 'Chest', 'compound', 'bilateral'),
  ('Med Ball Chest Pass', 'Chest', 'compound', 'bilateral'),
  ('Doorway Chest Stretch', 'Chest', 'mobility', 'bilateral'),
  ('Doorway Chest Stretch (deeper)', 'Chest', 'mobility', 'bilateral'),
  ('Doorway Chest Stretch + Overhead Reach', 'Chest', 'mobility', 'bilateral'),
  ('Doorway Chest Stretch + Rotation', 'Chest', 'mobility', 'bilateral'),
  ('DB Shoulder Press', 'Shoulders', 'compound', 'bilateral'),
  ('Overhead Press', 'Shoulders', 'compound', 'bilateral'),
  ('Overhead Press (moderate load)', 'Shoulders', 'compound', 'bilateral'),
  ('Overhead Press, seated, light DB', 'Shoulders', 'compound', 'bilateral'),
  ('Seated Overhead Press', 'Shoulders', 'compound', 'bilateral'),
  ('Shoulder Press (machine)', 'Shoulders', 'compound', 'bilateral'),
  ('Single-Leg Overhead Press', 'Shoulders', 'compound', 'unilateral'),
  ('Overhead Reach (functional)', 'Shoulders', 'mobility', 'bilateral'),
  ('Overhead Reach with Step', 'Shoulders', 'mobility', 'unilateral'),
  ('Isometric Shoulder External Rotation (band, light)', 'Shoulders', 'accessory', 'unilateral'),
  ('Rear Delt Fly (machine)', 'Shoulders', 'accessory', 'bilateral'),
  ('Lateral Raise (machine or light DB)', 'Shoulders', 'accessory', 'bilateral'),
  ('Single-Leg Front Raise', 'Shoulders', 'accessory', 'unilateral'),
  ('Bicep Curl (light DB)', 'Biceps', 'accessory', 'bilateral'),
  ('Bicep Curl (machine/cable)', 'Biceps', 'accessory', 'bilateral'),
  ('Bicep Curl, heavier DB', 'Biceps', 'accessory', 'bilateral'),
  ('DB Bicep Curl', 'Biceps', 'accessory', 'bilateral'),
  ('DB Bicep Curl (heavier)', 'Biceps', 'accessory', 'bilateral'),
  ('Single-Leg Bicep Curl', 'Biceps', 'accessory', 'unilateral'),
  ('DB Overhead Tricep Extension', 'Triceps', 'accessory', 'bilateral'),
  ('Tricep Pushdown (cable/machine)', 'Triceps', 'accessory', 'bilateral'),
  ('Hip Abduction (machine)', 'Abductors', 'accessory', 'bilateral'),
  ('Leg Curl (machine)', 'Hamstrings', 'accessory', 'bilateral'),
  ('Leg Extension (machine)', 'Quads', 'accessory', 'bilateral'),
  ('Leg Press (machine)', 'Quads', 'compound', 'bilateral'),
  ('Ball Leg Curl', 'Hamstrings', 'accessory', 'bilateral'),
  ('Glute Kickback (machine)', 'Glutes', 'accessory', 'unilateral'),
  ('Banded Clamshell', 'Glutes', 'accessory', 'unilateral'),
  ('Clamshell', 'Glutes', 'accessory', 'unilateral'),
  ('Calf Raise, balance-focused', 'Calves', 'accessory', 'bilateral'),
  ('Heel Raise, light resistance', 'Calves', 'accessory', 'bilateral'),
  ('Foam Roll: Full Lower Body', 'Full Body', 'mobility', 'bilateral'),
  ('Foam Roll: Full Posterior Chain', 'Hamstrings', 'mobility', 'bilateral'),
  ('Foam Roll: Quads & IT Band', 'Quads', 'mobility', 'bilateral'),
  ('Foam Roll: Quads / IT Band / Glutes', 'Quads', 'mobility', 'bilateral'),
  ('Foam Roll: Thoracic Spine', 'Back', 'mobility', 'bilateral'),
  ('Foam Roll: Thoracic Spine & Lats', 'Back', 'mobility', 'bilateral'),
  ('Foam Roll: Thoracic Spine & Shoulders', 'Back', 'mobility', 'bilateral'),
  ('Foam Roll: Upper Back & Lats', 'Back', 'mobility', 'bilateral'),
  ('Cat-Cow (spinal mobility)', 'Back', 'mobility', 'bilateral'),
  ('Cat-Cow + Multi-Plane Mobility', 'Back', 'mobility', 'bilateral'),
  ('Cat-Cow + Thoracic Rotation', 'Back', 'mobility', 'bilateral'),
  ('Cat-Cow / Segmental Spine Mobility', 'Back', 'mobility', 'bilateral'),
  ('Cat-Cow w/ Reach', 'Back', 'mobility', 'bilateral'),
  ('Thoracic Rotation (seated or standing)', 'Back', 'mobility', 'bilateral'),
  ('Thread the Needle + Reach', 'Back', 'mobility', 'unilateral'),
  ('Thread the Needle Stretch', 'Back', 'mobility', 'unilateral'),
  ('Kneeling Hip Flexor Stretch (PNF)', 'Adductors', 'mobility', 'unilateral'),
  ('Kneeling Hip Flexor Stretch (assisted)', 'Adductors', 'mobility', 'unilateral'),
  ('Kneeling Hip Flexor Stretch + Rotation', 'Adductors', 'mobility', 'unilateral'),
  ('Standing Calf Stretch', 'Calves', 'mobility', 'unilateral'),
  ('Standing Calf Stretch + Ankle Mobility', 'Calves', 'mobility', 'unilateral'),
  ('Standing Calf Stretch + Balance Reach', 'Calves', 'mobility', 'unilateral'),
  ('Standing Calf Stretch w/ Wall', 'Calves', 'mobility', 'unilateral'),
  ('Supine Figure-4 + Full-Body Stretch Flow', 'Glutes', 'mobility', 'unilateral'),
  ('Supine Figure-4 + Hamstring Stretch', 'Glutes', 'mobility', 'unilateral'),
  ('Supine Figure-4 Stretch', 'Glutes', 'mobility', 'unilateral'),
  ('Supine Figure-4 Stretch (deeper)', 'Glutes', 'mobility', 'unilateral'),
  ('Seated 90/90 Breathing + Pelvic Tilt', 'Core', 'mobility', 'bilateral'),
  ('Seated Dead Bug (supported)', 'Core', 'accessory', 'unilateral'),
  ('Seated Pallof Press (light)', 'Core', 'accessory', 'unilateral'),
  ('Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Dead Bug w/ Light DB', 'Core', 'accessory', 'unilateral'),
  ('Dead Bug w/ Moderate DB', 'Core', 'accessory', 'unilateral'),
  ('Bird Dog', 'Core', 'accessory', 'unilateral'),
  ('Bird Dog + Reach', 'Core', 'accessory', 'unilateral'),
  ('Bird Dog w/ Band', 'Core', 'accessory', 'unilateral'),
  ('Bird Dog, longer hold', 'Core', 'accessory', 'unilateral'),
  ('Hollow Hold', 'Core', 'accessory', 'bilateral'),
  ('Med Ball Rotational Throw', 'Core', 'compound', 'unilateral'),
  ('Overhead Med Ball Throw', 'Full Body', 'compound', 'bilateral'),
  ('Overhead Carry', 'Full Body', 'compound', 'bilateral'),
  ('Kettlebell Swing', 'Glutes', 'compound', 'bilateral'),
  ('Single-Leg Dead Bug', 'Core', 'accessory', 'unilateral'),
  ('Sit-to-Stand (chair, hands assisted as needed)', 'Full Body', 'compound', 'bilateral'),
  ('Sit-to-Stand to Short Walk', 'Full Body', 'compound', 'bilateral'),
  ('Sit-to-Stand to Walk, timed', 'Full Body', 'compound', 'bilateral'),
  ('Sit-to-Stand, slower tempo', 'Full Body', 'compound', 'bilateral')
) as v(name, muscle_group, movement_type, laterality)
where lower(e.name) = lower(v.name)
  and e.primary_muscle_group is null
  and e.movement_type is null
  and e.laterality is null;
