-- Upgrades the generic YouTube-search fallback (set in migration 0112)
-- to a real, specific demo link wherever this exercise's name matches
-- one in the coach's own "Functional Fitness Exercise Database"
-- reference spreadsheet (the same source migration 0043's bulk import
-- came from) -- 669 of the 965 bulk-imported exercises matched by name
-- and have a real video link in that source.
--
-- Only replaces a video_url that's still the generic search-link
-- fallback (starts with the search-results URL prefix) -- never
-- touches a link you've since hand-picked yourself.
update public.exercises e
set video_url = v.link
from (values
  ('Ab Wheel Kneeling Rollout', 'https://youtu.be/QB2Gj1QGfjQ'),
  ('Alternating Double Dumbbell Bent Over Row', 'https://youtu.be/UKjQMYiQnS0?si=Lg6kuQMDGFaxi6X7'),
  ('Alternating Double Dumbbell Incline Bench Prone Row', 'https://youtu.be/xkCR2CkkL1g?si=Qy0YPAcCasZF6kNk'),
  ('Alternating Double Dumbbell Prone Row', 'https://youtu.be/Ry9HwpfUbd8?si=oY89SBibCyKMJ7CT'),
  ('Alternating Double Dumbbell Thruster', 'https://youtu.be/NDA72gV21vM?si=nr1ibCzWJfLIYTXz'),
  ('Alternating Double Kettlebell Bent Over Row', 'https://youtu.be/jdx2kl5K0Ps?si=ABHltAh0E_8BUz7i'),
  ('Alternating Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/rAoi4_AI7VA?si=b6KXmXEYoxIPmTt2'),
  ('Alternating Double Kettlebell Prone Row', 'https://youtu.be/OD7URB1yHAo?si=UX_3VmEfO_WpeiuT'),
  ('Alternating Single Arm Dumbbell Pendlay Row', 'https://youtu.be/7zKQ79awAvY?feature=shared'),
  ('Alternating Single Arm Kettlebell Around the World', 'https://youtu.be/ekR7MDSWwEQ'),
  ('Alternating Single Arm Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/X8I4Uq4QgYE?si=0ZNJz2TPEC0nSZaa'),
  ('Alternating Single Arm Kettlebell Start Stop Swing', 'https://youtu.be/3Xhy3dz61to?si=8lmx3c2FvDHq6Zy5'),
  ('Alternating Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/BoihxFxtsyY?si=kZuvg9gJ179nJ1Xh'),
  ('Bar Eccentric Pull Up', 'https://youtu.be/T4Jv__fWjZ8?si=sbUarOu5VD7qBK4s'),
  ('Barbell Back Rack Split Squat', 'https://youtu.be/KXUJxb8hO8U'),
  ('Barbell Bent Over Row', 'https://youtu.be/9Gf-Ourup_k?si=qt-DlqHLDICtOmju'),
  ('Barbell Block Pull Deadlift', 'https://youtu.be/iVpVk8x-VDQ'),
  ('Barbell Box Back Squat', 'https://youtu.be/dLG78_Z9rjM'),
  ('Barbell Conventional Deadlift', 'https://youtu.be/op9kVnSso6Q'),
  ('Barbell Frog Pump', 'https://youtu.be/coFi5XRmTAk?si=b564Njzd_-7c0U9x'),
  ('Barbell Front Rack Split Squat', 'https://youtu.be/VsgCBIQE8gU?si=1KNObbTrjXSha2sF'),
  ('Barbell Glute Bridge', 'https://youtu.be/6EhYj5eSngY'),
  ('Barbell Halting Deadlift', 'https://youtu.be/0LrH7uHRGxI'),
  ('Barbell High Bar Back Squat', 'https://youtu.be/ultWZbUMPL8'),
  ('Barbell Hip Thrust', 'https://youtu.be/5S8SApGU_Lk'),
  ('Barbell Inverted Row', 'https://youtu.be/bHO0A4ZF_Zg'),
  ('Barbell Pendlay Row', 'https://youtu.be/ezrZnmjZTR4'),
  ('Barbell Prone Row', 'https://youtu.be/pJzThQgKKxw'),
  ('Barbell Rack Pull', 'https://youtu.be/zdaEWO0S5HU'),
  ('Barbell Reverse Grip Bent Over Row', 'https://youtu.be/cZvQNvTUUu0?si=SqA3lYAZBc0jOnvn'),
  ('Barbell Romanian Deadlift', 'https://youtu.be/LURGDIX3adY?si=fHh3AAX-mZB09HXi'),
  ('Barbell Stiff Legged Deadlift', 'https://youtu.be/5_t0SsovgW8?si=5Zg1x855TTmrp1cL'),
  ('Barbell Sumo Back Squat', 'https://youtu.be/qiQAsB0x-7k?si=OlWu0ou6Vr0NnuvE'),
  ('Barbell Sumo Deadlift', 'https://youtu.be/wQHSYDSgDn8'),
  ('Battle Rope Alternating Side Slam', 'https://youtu.be/0ieiwGvtCT4?si=eBnoeYkD7iu_tawZ'),
  ('Battle Rope Power Slam', 'https://youtu.be/7wDx6mZDxA8?si=rDE21yzc81AXz5sw'),
  ('Battle Rope Russian Twist', 'https://youtu.be/_-kclLM0Mak'),
  ('Bodyweight Alternating Cossack Squat', 'https://youtu.be/dhDjKmTX8tU'),
  ('Bodyweight Alternating Curtsy Lunge', 'https://youtu.be/SNtgnXpolPY?si=RQdshbRrgML5pKNu'),
  ('Bodyweight Alternating Forward Lunge', 'https://youtu.be/0RqJM6GM5bg?si=eL5TvNrMzUaI1oOW'),
  ('Bodyweight Alternating Heel Taps', 'https://youtu.be/URWXz0DmE7s'),
  ('Bodyweight Alternating Lateral Bench Jump', 'https://youtu.be/pVoOtkGBN6s'),
  ('Bodyweight Alternating Lateral Lunge', 'https://youtu.be/FvJS_MSN4Lo?si=Z7h-t5HEEQC6trw6'),
  ('Bodyweight Alternating Reverse Lunge', 'https://youtu.be/OX0fKkaY6_c?si=T0Ta2iyvXrGIGA7w'),
  ('Bodyweight Alternating Russian Step Up', 'https://youtu.be/uWQaD_zDNP8?si=e7uAr4KO-Uxs3C4h'),
  ('Bodyweight Alternating Single Leg V Up', 'https://youtu.be/0EIDVDbzVNo?si=B73itVIXJWWYaH0C'),
  ('Bodyweight Alternating Single Leg Wall Sit', 'https://youtu.be/eYGszeFcI7Y?si=jFOFuzza1JQMYuVE'),
  ('Bodyweight Alternating Step Up', 'https://youtu.be/lUSmIRNqt9w?si=2Uzz5dQAroAGZKAK'),
  ('Bodyweight Bear Crawl', 'https://youtu.be/8y-C1wUb-3c'),
  ('Bodyweight Bent Knee Copenhagen Plank', 'https://youtu.be/obtdLUWZi-Y'),
  ('Bodyweight Bent Knee Reverse Hyperextension', 'https://youtu.be/RbkVHCMU3xU'),
  ('Bodyweight Bent Knee Windshield Wiper', 'https://youtu.be/8ruEIfBzLrw?si=smM0Bo6E_xDv-x1e'),
  ('Bodyweight Bicycle Crunch', 'https://youtu.be/fHXcyedPCPo?si=haa5Z5z5wbVY6loh'),
  ('Bodyweight Bird Dog', 'https://youtu.be/tU-WZsouVjo?si=Ti1JUU03OqgnmtX6'),
  ('Bodyweight Bird Dog Knee to Elbow', 'https://youtu.be/1v4_Vsvk3gc'),
  ('Bodyweight Box Pistol Squat', 'https://youtu.be/Ly71LeprFKQ'),
  ('Bodyweight Bulgarian Split Squat', 'https://youtu.be/kBQ1krvKFBU'),
  ('Bodyweight Butterfly Sit Up', 'https://youtu.be/ZLyOWSPnVrM'),
  ('Bodyweight Copenhagen Plank', 'https://youtu.be/tKb76R21AfM?si=zsuYyzMMfjZleCpc'),
  ('Bodyweight Cossack Squat', 'https://youtu.be/lyMHR7F8lPA?si=An72TBlVkZQu4GMO'),
  ('Bodyweight Crunch', 'https://youtu.be/Gala3hWxFTw?si=5Qrh2TKQB1NMQpCG'),
  ('Bodyweight Curtsy Lunge', 'https://youtu.be/cXHnXTR79Kw?si=HidnQgZQ02ZN6GNc'),
  ('Bodyweight Cyclist Squat', 'https://youtu.be/BAlXJ5lLMAA?si=H1cfMWF52YWOMraL'),
  ('Bodyweight Dead Bug', 'https://youtu.be/jbWmbhElf3Q'),
  ('Bodyweight Extended Range Side Lying Hip Abduction', 'https://youtu.be/s6API4Yeqxs?si=apjN7JBTfdY-DW16'),
  ('Bodyweight Face the Wall Squat', 'https://youtu.be/pktIjwNiuYE?si=fWFt85clM0T2gopP'),
  ('Bodyweight Feet Elevated Frog Pump', 'https://youtu.be/K2AvS_4hjd4?si=WeXgOnAQd6Db4L-d'),
  ('Bodyweight Feet Elevated Glute Bridge', 'https://youtu.be/kFvF6ZHv-KI'),
  ('Bodyweight Feet Elevated Russian Twist', 'https://youtu.be/WT9UCB_1Y8Q?si=dmkzRkM-dzlFe1ux'),
  ('Bodyweight Fire Hydrant', 'https://youtu.be/IFrN8GELc-k?feature=shared'),
  ('Bodyweight Foot Elevated Cossack Squat', 'https://youtu.be/DgJtQJxYVTk'),
  ('Bodyweight Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/Gu4qA5TevLU'),
  ('Bodyweight Forearm Plank', 'https://youtu.be/YvUw_mKMGfQ?feature=shared'),
  ('Bodyweight Forward Lunge', 'https://youtu.be/1XKXGRQX-0w?si=hoLOL3F63ye-LGkD'),
  ('Bodyweight Frog Pump', 'https://youtu.be/7IVoH7E4rWo'),
  ('Bodyweight Frog Reverse Hyperextension', 'https://youtu.be/zH8QN413Vuo?si=htM_QtEmupefpV2z'),
  ('Bodyweight Glute Bridge', 'https://youtu.be/ncpMkhXAykg?si=a_b3ot2rsThtz4DE'),
  ('Bodyweight Glute Bridge Isometric with Alternating Single Leg Extension', 'https://youtu.be/cRCXEFhpBEI?si=6A2YpBsXM9WqT6rW'),
  ('Bodyweight Hamstring Walkout', 'https://youtu.be/GcV2LB0qqnY?si=PoIiYCAOL0uaDuPR'),
  ('Bodyweight Hand Assisted Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/hTBEkHf8GmA'),
  ('Bodyweight Hand Assisted Knee Over Toe Split Squat', 'https://youtu.be/gBSQOdjjKcc?si=oEXgjHk6m5c-o7MS'),
  ('Bodyweight Hand Assisted Sissy Squat', 'https://youtu.be/nNAssQ-4HjA?si=wsCriUBiz-jLsGEk'),
  ('Bodyweight Hand Assisted Skater Squat', 'https://youtu.be/DExb7UaAlbg'),
  ('Bodyweight Hand Assisted Split Squat', 'https://youtu.be/WRCsxtCfrEE'),
  ('Bodyweight Hip Thrust', 'https://youtu.be/OAhvIWLC0rc'),
  ('Bodyweight Hollow Body Flutter Kicks', 'https://youtu.be/-UVAa92y1r4?si=CIm_rryJMtDs0TPj'),
  ('Bodyweight Hollow Body Hold', 'https://youtu.be/4xRpGgttca8'),
  ('Bodyweight In and Out Squat Jump', 'https://youtu.be/5KT8dr-J65U?si=YGtdHgvAy0DIgmt5'),
  ('Bodyweight Isometric Split Squat Hold', 'https://youtu.be/36kJjDfMHIc?feature=shared'),
  ('Bodyweight Knee Over Toe Split Squat', 'https://youtu.be/ufsoFnFCqA4'),
  ('Bodyweight Kneeling Forearm Plank', 'https://youtu.be/Ns1NS9ThNhI'),
  ('Bodyweight Kneeling Side Plank', 'https://youtu.be/PAHxwhBVsYY?si=pym-tzPNwmH8zNeP'),
  ('Bodyweight Kneeling Side Plank Clamshell', 'https://youtu.be/0BhP8_plU_U?si=KupbrDjjj8HjKMrv'),
  ('Bodyweight Lateral Bear Crawl', 'https://youtu.be/JLtXEZAwNxQ?feature=shared'),
  ('Bodyweight Lateral Lunge', 'https://youtu.be/vwOrd9umMOc?si=dTiEBNYBRJajSW4a'),
  ('Bodyweight Low Switch Cossack Squat', 'https://youtu.be/sj_bFtL9Oy4?si=osmoYlG_O5Fs6lPE'),
  ('Bodyweight Mountain Climber', 'https://youtu.be/kLh-uczlPLg?si=WfwS9PlCOc9d1t1N'),
  ('Bodyweight Oblique Crunch', 'https://youtu.be/teZDcxypX54?si=5hPKSeI_xcW5yftV'),
  ('Bodyweight Pivot Split Squat', 'https://youtu.be/laMvUTGs0-k?si=zazYAAhek_WWCwAN'),
  ('Bodyweight Prone Cobra', 'https://youtu.be/NZSBjpVpvw8?si=lyk8zIAtzX2ETUc_'),
  ('Bodyweight Quadruped Hip Extension', 'https://youtu.be/1UwyzWjFx5k'),
  ('Bodyweight Reverse Crunch', 'https://youtu.be/aIyadD7d7OA?si=I96m4yP0SA4lVKvH'),
  ('Bodyweight Reverse Hyperextension', 'https://youtu.be/UP44YFNMF4A?si=ymXfKPXP3jXmkT4j'),
  ('Bodyweight Reverse Lunge', 'https://youtu.be/U7Nrwyu6Uqo?si=i10Myq56LE1Wlzzn'),
  ('Bodyweight Reverse Plank', 'https://youtu.be/_oFQ3G5iwtc?si=3F2p69DpOKAmGXoE'),
  ('Bodyweight Russian Step Up', 'https://youtu.be/T0aGAd4z8_g?si=LLndgNIkangYyqvf'),
  ('Bodyweight Russian Twist', 'https://youtu.be/m-dlg3v8SkY?si=KI1hgOAtTqI0ty6r'),
  ('Bodyweight Seated Ab Circles', 'https://youtu.be/GflQ_ymx9Nw'),
  ('Bodyweight Side Lying Clamshell', 'https://youtu.be/G3yQITNPIz8?si=V_AVSgSWE_RFAsSE'),
  ('Bodyweight Side Lying Hip Abduction', 'https://youtu.be/m6dHgVYxAyc?si=NjK1qTP-dcOSCced'),
  ('Bodyweight Side Lying Hip Adduction', 'https://youtu.be/UW52u8OaWhw?si=WdEOpAR_PSB9x9bR'),
  ('Bodyweight Side Plank', 'https://youtu.be/_R389Jk0tIo'),
  ('Bodyweight Side Plank Reach Through', 'https://youtu.be/7lfNb_zydvQ'),
  ('Bodyweight Single Leg Foot Elevated Glute Bridge', 'https://youtu.be/I7Zwyzr8COk'),
  ('Bodyweight Single Leg Glute Bridge', 'https://youtu.be/z4J188sFD4g'),
  ('Bodyweight Single Leg Hip Thrust', 'https://youtu.be/1Dbd7wStRJg?si=Yx13oEQ5A4kl4YJ5'),
  ('Bodyweight Sit Up', 'https://youtu.be/bT8NVeDvuQg?si=paUR-bam-jwd-xPx'),
  ('Bodyweight Split Squat', 'https://youtu.be/-aMgxO760L4?si=9gx0HVA_RdsNSgFi'),
  ('Bodyweight Squat', 'https://youtu.be/C_VtOYc6j5c'),
  ('Bodyweight Squat to Bench', 'https://youtu.be/93l0NGCosAE'),
  ('Bodyweight Step Up', 'https://youtu.be/V9ButqpLLcw?si=W7rot5ocLsfGP3zd'),
  ('Bodyweight Supine Alternating Single Leg Raise', 'https://youtu.be/IUCoqgdvDxU?si=8xtgp1M-mJqke2mR'),
  ('Bodyweight Supine Leg Raise', 'https://youtu.be/q0JVBRHoLz4'),
  ('Bodyweight Tuck Jump', 'https://youtu.be/vgB_eWuvGW8?si=anQ4gfG2ik-Y_uU9'),
  ('Bodyweight V Up', 'https://youtu.be/7UVgs18Y1P4?si=o0GvxxE-1wAYvgfE'),
  ('Bodyweight Walking Lunge', 'https://youtu.be/tlbTz6IamaE'),
  ('Bodyweight Wall Sit', 'https://youtu.be/SszDMOZvFuw'),
  ('Bodyweight Wall Slide Squat', 'https://youtu.be/3J99J5NxNSQ?si=Xv_W-o9GzT-nvtVQ'),
  ('Bodyweight Windmill', 'https://youtu.be/87I2gbRgtUI?si=4hUJ0N3X8wu8MMKC'),
  ('Bodyweight Windshield Wiper', 'https://youtu.be/XXcRdXIw0go?si=y-Sh6yOZyvTpiN50'),
  ('Bulgarian Bag Back Rack Alternating Cossack Squat', 'https://youtu.be/wqXP71ooU44?si=oje6--5yoC_aZeha'),
  ('Bulgarian Bag Back Rack Alternating Forward Lunge', 'https://youtu.be/a8y1Qwir7YQ?si=izeBmxPLl4E0ekvy'),
  ('Bulgarian Bag Back Rack Alternating Lateral Lunge', 'https://youtu.be/fJePN1sD5ok?si=g-YYXG1x8L53Vuv-'),
  ('Bulgarian Bag Back Rack Curtsy Lunge', 'https://youtu.be/6Y7jLhsURck?si=ZI60iuhlYRh4x0Ul'),
  ('Bulgarian Bag Back Rack Forward Lunge', 'https://youtu.be/GRFb4uKia9o?si=12NJKTAJm5VqsZCt'),
  ('Bulgarian Bag Back Rack Reverse Lunge', 'https://youtu.be/RqMG5v-jUyE?si=hxI8O10U-7CcGVRp'),
  ('Bulgarian Bag Back Rack Split Squat', 'https://youtu.be/VI6qhpokyPI?si=vlQYMvQBOEZ4sjof'),
  ('Bulgarian Bag Back Rack Squat', 'https://youtu.be/ctrXJi1QgEQ?si=O95czG8N3RjyL-Y-'),
  ('Bulgarian Bag Back Rack Walking Lunge', 'https://youtu.be/FNr5JBGrJTU?si=bn24rl-sBOt5WTfx'),
  ('Bulgarian Bag Front Rack Squat', 'https://youtu.be/jAo338cgsmU?si=1dPZPEL1g1HDUuIC'),
  ('Bulgarian Bag Swing', 'https://youtu.be/Q7rAfqN-NH0?si=zEMPL2_L-ZEUhtLj'),
  ('Bulgarian Bag Thruster', 'https://youtu.be/-Am9J90oDK4?si=DzyEzfiwzZAs3ckF'),
  ('Cable Fire Hydrant', 'https://youtu.be/P4cP-juNM1Q'),
  ('Cable Glute Kickback', 'https://youtu.be/qJxwJ1e1HxI?si=5y999i_uPybFFDol'),
  ('Cable Half Kneeling Pallof Press', 'https://youtu.be/7JBR6JGE1hY'),
  ('Cable Hip Abduction', 'https://youtu.be/saVSMtIttZE?si=qgSuj5ww8uiz2Wkd'),
  ('Cable Hip Adduction', 'https://youtu.be/UyXncDziNGo?si=W4GuZaUvoWtiIOxj'),
  ('Cable Hip Rotation', 'https://youtu.be/ApvO0XTFjRc'),
  ('Cable Kneeling Crunch', 'https://youtu.be/ToJeyhydUxU'),
  ('Cable Pallof Press', 'https://youtu.be/tvzoG7Ua05Y?si=-i5BoLWWqI_tGovS'),
  ('Cable Prone Bench Hamstring Curl', 'https://youtu.be/IalP0lgYPnc'),
  ('Cable Prone Bench Single Leg Hamstring Curl', 'https://youtu.be/l66EvN4X6Mk?si=i4fPkqXo_4_8fmO6'),
  ('Cable Prone Hamstring Curl', 'https://youtu.be/qOu-89KQsIg?si=NzRrmfpYz9Rwpoy8'),
  ('Cable Prone Single Leg Hamstring Curl', 'https://youtu.be/k6Vo8hBLypQ'),
  ('Cable Pull Through', 'https://youtu.be/NEDrQPoITMc?si=ZeJ1LOUbzrjgk-_8'),
  ('Cable Quadruped Hip Abduction', 'https://youtu.be/MZi0M3OJEVw'),
  ('Cable Reverse Crunch', 'https://youtu.be/3Mn_4KTDTi0?si=3zBBQ33AQDN7XPp4'),
  ('Cable Reverse Grip Lat Pulldown', 'https://youtu.be/zLKwAYUmGMc'),
  ('Cable Rope Pullover', 'https://youtu.be/eAklBxVmR6w?si=FCt-1WsfkCKhD2P_'),
  ('Cable Seated Crunch', 'https://youtu.be/gQT76pz_X9Y'),
  ('Cable Single Leg Standing Bent Knee Hip External Rotation', 'https://youtu.be/1OnBBhiaQjY'),
  ('Cable Standing Single Leg Hamstring Curl', 'https://youtu.be/tkh43Yc0tEs'),
  ('Cable Straight Bar Pullover', 'https://youtu.be/SgzJGLlAtok?si=p2bo--kETp2ajVVX'),
  ('Cable Tall Kneeling Pallof Press', 'https://youtu.be/EtEPKajf0PE'),
  ('Cable Tall Kneeling Pull Through', 'https://youtu.be/5mkpuBI-2Ls'),
  ('Cable V Grip Lat Pulldown', 'https://youtu.be/8hzVLzu-RJk'),
  ('Cable V Grip Seated Floor Lat Pulldown', 'https://youtu.be/wo-YhhSpEJI'),
  ('Cable V Grip Seated Low Row', 'https://youtu.be/EhAho9Szp-0'),
  ('Cable Wide Grip Lat Pulldown', 'https://youtu.be/UWhyxvCCzhw'),
  ('Clubbell Barbarian Squat', 'https://youtu.be/SnRUNmL46So?si=LiGATOKJlrhb676E'),
  ('Clubbell Order Alternating Reverse Lunge', 'https://youtu.be/dNrYT5iU7BQ?si=VgjB2U40EdHaPV2P'),
  ('Clubbell Order Cyclist Squat', 'https://youtu.be/_ckOSXnMuXo?si=ljb43FTe1n7YBdl8'),
  ('Clubbell Order Forward Lunge', 'https://youtu.be/mVJyt-hJqQ4?si=ZyQU-rcyvqeQG8GO'),
  ('Clubbell Pullover', 'https://youtu.be/0sRFLvzcqxw?si=cqK8W0uEQdEUfDAy'),
  ('Clubbell Shoulder Park Squat', 'https://youtu.be/oNZnCluUrjQ?si=NER_BSsVDrgi7GOm'),
  ('Clubbell Swing', 'https://youtu.be/9JHFkrjW4_Y?si=m1HLdDm33Jymv5KP'),
  ('DB Overhead Tricep Extension', 'https://youtu.be/7h3lG2WnLXg'),
  ('Double Clubbell Barbarian Squat', 'https://youtu.be/rkB05p8JKDc?si=pJNkF5RP4J1kn_LL'),
  ('Double Clubbell Clean', 'https://youtu.be/XRyFEfRbHYY?si=9uHqeQJHtoWY-upd'),
  ('Double Clubbell Pullover', 'https://youtu.be/2ZYphWzJedw?si=f5GGOhThihsKqIds'),
  ('Double Dumbbell Bent Over Row', 'https://youtu.be/6gvmcqr226U?si=Ubc_zUNwRYINkZSI'),
  ('Double Dumbbell Cyclist Thruster', 'https://youtu.be/qoswYkyJG-I?si=Jigh3MmNt7IIj-BA'),
  ('Double Dumbbell Front Rack Alternating Cossack Squat', 'https://youtu.be/JFeG8YiLYmk'),
  ('Double Dumbbell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/1VkEZirajQQ?si=4EJltD-xdvd_ifWT'),
  ('Double Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/Ambx6K-_AfY?si=2pUqPVUnlmZLMMwH'),
  ('Double Dumbbell Front Rack Alternating Lateral Lunge', 'https://youtu.be/V-crv5-Tqbg?si=k00dfu1tLmH4-h3a'),
  ('Double Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1iT74xBv0LA?si=vNMiZEtQ8W3QCkqc'),
  ('Double Dumbbell Front Rack Alternating Step Up', 'https://youtu.be/anHX8Zp67C8?si=qbb7ETCqekLaflB_'),
  ('Double Dumbbell Front Rack Carry', 'https://youtu.be/dDq_T_H8h5E?si=g4wZK9kvKsPxqI3d'),
  ('Double Dumbbell Front Rack Cossack Squat', 'https://youtu.be/ZxjMX7k3Zp0?si=pZtrI1oUYV-FsjgX'),
  ('Double Dumbbell Front Rack Curtsy Lunge', 'https://youtu.be/ORgVFXTysI8?si=F2L2x6t0lsu7RXmy'),
  ('Double Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/QV4DL31Ch94?si=6O9QTMoEB9MtwsZY'),
  ('Double Dumbbell Front Rack Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/7obV55SSiaw?si=S805NWBkc0FbMt7c'),
  ('Double Dumbbell Front Rack Forward Lunge', 'https://youtu.be/gqAaDuZQjXY?si=XpGry05ejKZXpsz-'),
  ('Double Dumbbell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/WQUXh0Zk1XU?si=nWvh_443nHiOu2bH'),
  ('Double Dumbbell Front Rack Lateral Lunge', 'https://youtu.be/yX1XqdeaczU?si=-zoUhOUe3G-CUM4q'),
  ('Double Dumbbell Front Rack Reverse Lunge', 'https://youtu.be/Zv8CDt76v-o?si=2EUkwtXgQzLAb65b'),
  ('Double Dumbbell Front Rack Split Squat', 'https://youtu.be/Bf4HVTwMjkc?si=j0OgjVc5PW-T2bs6'),
  ('Double Dumbbell Front Rack Squat', 'https://youtu.be/B86Zj72LwzA'),
  ('Double Dumbbell Front Rack Step Up', 'https://youtu.be/hKLIHPXmPA4?si=mk9hkktF_4qw0okV'),
  ('Double Dumbbell Front Rack Walking Lunge', 'https://youtu.be/i3qlK1vA0z4?si=LCNdYUF9IbCDWnYm'),
  ('Double Dumbbell Incline Bench Prone Row', 'https://youtu.be/93ZAdx24QVQ'),
  ('Double Dumbbell Low Hold Alternating Cossack Squat', 'https://youtu.be/k6L3kWztcNs?si=GiG4ZJIK5HCWo7Rm'),
  ('Double Dumbbell Low Hold Lateral Lunge', 'https://youtu.be/HLDhxSqMQyE?si=3iYb1Ys4Ld0KFpSn'),
  ('Double Dumbbell Pendlay Row', 'https://youtu.be/4-Jz3c_u1dw'),
  ('Double Dumbbell Prone Row', 'https://youtu.be/scf3uLuAATg'),
  ('Double Dumbbell Romanian Deadlift', 'https://youtu.be/Cf3CaHui43A?si=dFPcP6jQEQECmXmY'),
  ('Double Dumbbell Seated Good Morning', 'https://youtu.be/x5nnk8hUBo4'),
  ('Double Dumbbell Seesaw Bent Over Row', 'https://youtu.be/BD5mTDoy2UE?si=00skC1JcPnkjtd86'),
  ('Double Dumbbell Staggered Stance Romanian Deadlift', 'https://youtu.be/RFuCfiMfJ1w'),
  ('Double Dumbbell Suitcase Alternating Curtsy Lunge', 'https://youtu.be/SQHyEoZLd1o?si=_TJYUJVzm_zR7ZxZ'),
  ('Double Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/t7DBjlOTwAk'),
  ('Double Dumbbell Suitcase Alternating Lateral Lunge', 'https://youtu.be/GkgTBlp417A?si=2RKL7GSC-wlwXQrE'),
  ('Double Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/Lsen4vH1nm8'),
  ('Double Dumbbell Suitcase Alternating Russian Step Up', 'https://youtu.be/7xKPC6fiAnI?si=AjBy--nHV9jih9q4'),
  ('Double Dumbbell Suitcase Alternating Step Up', 'https://youtu.be/R61TjoYofDE?si=sA8kbakWIt24ow1A'),
  ('Double Dumbbell Suitcase Curtsy Lunge', 'https://youtu.be/tKQAKx25kyk?si=CVIu5jUCBGlS-CU4'),
  ('Double Dumbbell Suitcase Cyclist Squat', 'https://youtu.be/1ij5SfH4PMo?si=HuKVOjAkOpK16kCi'),
  ('Double Dumbbell Suitcase Deadlift', 'https://youtu.be/29MJct32_6Y?si=ItNGT0m2qUZTy4_O'),
  ('Double Dumbbell Suitcase Deficit Split Squat', 'https://youtu.be/jqWAqPQvqAk'),
  ('Double Dumbbell Suitcase Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/h_S_Bb9rWCE?si=Dr_V3tDtxcRysPGX'),
  ('Double Dumbbell Suitcase Forward Lunge', 'https://youtu.be/9gglI77Kzq8?si=_dDcU05y48tssEAF'),
  ('Double Dumbbell Suitcase Knee Over Toe Split Squat', 'https://youtu.be/2U58iHm7oSM'),
  ('Double Dumbbell Suitcase Lateral Lunge', 'https://youtu.be/HLDhxSqMQyE'),
  ('Double Dumbbell Suitcase Reverse Lunge', 'https://youtu.be/a3wg2b8pd_w?si=UH9NFJeHHPoQpalx'),
  ('Double Dumbbell Suitcase Russian Step Up', 'https://youtu.be/OpEgnt3M98k?si=98bk34oOvELlwHao'),
  ('Double Dumbbell Suitcase Split Squat', 'https://youtu.be/yqH8u037IjM'),
  ('Double Dumbbell Suitcase Step Up', 'https://youtu.be/37tVohr7LcE'),
  ('Double Dumbbell Suitcase Walking Lunge', 'https://youtu.be/KdE6b_r7wxA'),
  ('Double Dumbbell Thruster', 'https://youtu.be/u3wKkZjE8QM'),
  ('Double Kettlebell Bent Over Row', 'https://youtu.be/t7dkLHdZ9uM?si=2TNd4Es589Vlu5uz'),
  ('Double Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/vcMZNgn5G9c'),
  ('Double Kettlebell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/UnevKvSIDLo?si=Y2g3UwUxqNMlZHdo'),
  ('Double Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/KIDRnwRAKAY?si=b00pYocO2xqWBGiJ'),
  ('Double Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/TzuHADj8h4M?si=tAyLqN0pCIXqxity'),
  ('Double Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/JKk87eVdbG8?si=Est-myfua9sI06NN'),
  ('Double Kettlebell Front Rack Alternating Russian Step Up', 'https://youtu.be/-L2RxqXxw3w?si=c5bWCZNShpG6g4Zw'),
  ('Double Kettlebell Front Rack Alternating Step Up', 'https://youtu.be/efg-AS2o3lM?feature=shared'),
  ('Double Kettlebell Front Rack Carry', 'https://youtu.be/iD8tG0qfztk?si=Z2QMS4VxJJkJ-kUk'),
  ('Double Kettlebell Front Rack Cossack Squat', 'https://youtu.be/sBuAJggOIxE?si=CST2KlC-8f_fnogp'),
  ('Double Kettlebell Front Rack Curtsy Lunge', 'https://youtu.be/b10GH56Feuc?si=DTF4gfUaKajgDIEP'),
  ('Double Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/xkL1f4yewf0'),
  ('Double Kettlebell Front Rack Forward Lunge', 'https://youtu.be/s-lZimLr_tg?si=Esmu-85tbaGWBDHx'),
  ('Double Kettlebell Front Rack Knee Over Toe Split Squat', 'https://youtu.be/G7e7EenICzQ'),
  ('Double Kettlebell Front Rack Lateral Lunge', 'https://youtu.be/TzuHADj8h4M?si=iwVlpYdKhmpx03MU'),
  ('Double Kettlebell Front Rack Reverse Lunge', 'https://youtu.be/PwtxLgNobQQ?si=DoSwEK_jWEv76qX3'),
  ('Double Kettlebell Front Rack Russian Step Up', 'https://youtu.be/KuNBOsyKvNs?si=xGQdh89b83Z6zfD1'),
  ('Double Kettlebell Front Rack Split Squat', 'https://youtu.be/ExJCssj4YV0'),
  ('Double Kettlebell Front Rack Squat', 'https://youtu.be/JoT4bHnzTMw?si=i8z5wbuObKGVIl4_'),
  ('Double Kettlebell Front Rack Step Up', 'https://youtu.be/wcnuhd6RHwE'),
  ('Double Kettlebell Front Rack Walking Lunge', 'https://youtu.be/Xmfx1eZMKmY'),
  ('Double Kettlebell Gorilla Row', 'https://youtu.be/Ln1j7lm6SrE'),
  ('Double Kettlebell Incline Bench Prone Row', 'https://youtu.be/jHpBzpxK16c?si=3sB9wGkke_B632ad'),
  ('Double Kettlebell Mountain Climber', 'https://youtu.be/AHwcb1JLtp4?si=XfL4K_pZpBu8QsfO'),
  ('Double Kettlebell Outside Swing', 'https://youtu.be/zrvtXpwVTOI'),
  ('Double Kettlebell Pendlay Row', 'https://youtu.be/KoOmLu7ms1s'),
  ('Double Kettlebell Prone Row', 'https://youtu.be/hUG_dolsaPE?si=_fw03cFT8VfLVtzo'),
  ('Double Kettlebell Romanian Deadlift', 'https://youtu.be/Xa8hHIwOHe4'),
  ('Double Kettlebell Seesaw Bent Over Row', 'https://youtu.be/Ej-Imk_vGeQ?si=XXtAfuJDxAf0G8hk'),
  ('Double Kettlebell Start Stop Swing', 'https://youtu.be/sS-bxWAoPWk?si=zgyeJNYUfOuTOFyj'),
  ('Double Kettlebell Suitcase Alternating Curtsy Lunge', 'https://youtu.be/XE7MrZADkr4?si=F2dW-lk_yYLoGHjE'),
  ('Double Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/oeyAEgHBVYc?si=mHjzSFPeM2YyoC0H'),
  ('Double Kettlebell Suitcase Alternating Lateral Lunge', 'https://youtu.be/zO8xPAa4-cY?si=bSfD4Gd8EdQ631Hq'),
  ('Double Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/FKrUoffD_W4?si=d07P0wkoguJqTTRV'),
  ('Double Kettlebell Suitcase Alternating Step Up', 'https://youtu.be/LQOGjjbAF6w?si=YO-bbJpBtYiLPA1T'),
  ('Double Kettlebell Suitcase Curtsy Lunge', 'https://youtu.be/DEE806Xr4V4?si=Bi_n7QfcYh1KpvBP'),
  ('Double Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/6caQpfXMvyw?si=WY0XcdcIUuE20g-o'),
  ('Double Kettlebell Suitcase Deadlift', 'https://youtu.be/aXwilZfmDyo'),
  ('Double Kettlebell Suitcase Forward Lunge', 'https://youtu.be/dgdMXVeApVM?si=C53j2jhBQ-HcBkp2'),
  ('Double Kettlebell Suitcase Knee Over Toe Split Squat', 'https://youtu.be/IJXzXAy4T24?si=DdfzxAdOIPYNJSOh'),
  ('Double Kettlebell Suitcase Reverse Lunge', 'https://youtu.be/zZfh3tvp5CI?feature=shared'),
  ('Double Kettlebell Suitcase Russian Step Up', 'https://youtu.be/N3HnkJ4Sp2s?si=L6L1BDMG1XO5MO94'),
  ('Double Kettlebell Suitcase Split Squat', 'https://youtu.be/lQH6gx3-q8E?si=ySQAsX-z8SQ9haRk'),
  ('Double Kettlebell Suitcase Step Up', 'https://youtu.be/3HUEab31fks?si=B2OmGKfwSuXhts1z'),
  ('Double Kettlebell Suitcase Walking Lunge', 'https://youtu.be/OFSepehKEsg?si=cACSI6X-vniOrBik'),
  ('Double Kettlebell Sumo Deadlift', 'https://youtu.be/4m288BpgfcQ'),
  ('Double Kettlebell Thruster', 'https://youtu.be/5-mxMxigTfw'),
  ('Dumbbell Crush Grip Bent Over Row', 'https://youtu.be/ppmAYXaz0_k'),
  ('Dumbbell Crush Grip Front Rack Squat', 'https://youtu.be/00Dc5QnwzGI?feature=shared'),
  ('Dumbbell Crush Grip Romanian Deadlift', 'https://youtu.be/SozT7TcG-p0?si=8DX3-uViiOfh2BvX'),
  ('Dumbbell Feet Elevated Frog Pump', 'https://youtu.be/67HLZ2-3_v0?si=57cdzDwX0TrSRLYm'),
  ('Dumbbell Frog Pump', 'https://youtu.be/N6t2Fv0SKGc'),
  ('Dumbbell Glute Bridge', 'https://youtu.be/JpDDoINkrog'),
  ('Dumbbell Goblet Alternating Cossack Squat', 'https://youtu.be/glbP_VzHNkw?si=1k1fGSYRRORQv7W8'),
  ('Dumbbell Goblet Alternating Curtsy Lunge', 'https://youtu.be/rzwJACyQNas?si=VKxH9lJuYtpzFxQo'),
  ('Dumbbell Goblet Alternating Forward Lunge', 'https://youtu.be/MjHkEW-AMQI?si=EyW7vqzwyfCJv1bN'),
  ('Dumbbell Goblet Alternating Lateral Lunge', 'https://youtu.be/xFvob3P7I74?si=o6y90mzLlkb5kjLo'),
  ('Dumbbell Goblet Alternating Reverse Lunge', 'https://youtu.be/YidVOnuiDfc?si=ECuN-ZTMBkyH_maZ'),
  ('Dumbbell Goblet Alternating Russian Step Up', 'https://youtu.be/e-VjvaI7FEI?si=Uc1Aq16WW3xsbpcO'),
  ('Dumbbell Goblet Alternating Step Up', 'https://youtu.be/gcP-jawjJ0s?si=kFE3ztEzT7nJwF3I'),
  ('Dumbbell Goblet Carry', 'https://youtu.be/qa-CYBhvSDA?si=qbgdCK6xq_Ftfez0'),
  ('Dumbbell Goblet Cossack Squat', 'https://youtu.be/qxb36LOiBsc?si=9n0Wr7YfIHCom-_w'),
  ('Dumbbell Goblet Curtsy Lunge', 'https://youtu.be/sMUQOGVrmQM?si=shRczfTH98OihNfr'),
  ('Dumbbell Goblet Cyclist Squat', 'https://youtu.be/2WxpkosHXLg?si=kPBJD_6N8w568qJ-'),
  ('Dumbbell Goblet Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/H5KGoSK1TMw?si=wfO6lfzcy7AhIt-M'),
  ('Dumbbell Goblet Forward Lunge', 'https://youtu.be/Q2ELBxwUp28?si=SahPctazGJoXnzHQ'),
  ('Dumbbell Goblet Knee Over Toe Split Squat', 'https://youtu.be/JlcQSTjIpk8?feature=shared'),
  ('Dumbbell Goblet Lateral Lunge', 'https://youtu.be/Vfl-OUHFQQo?si=zECktY2dytdpOMdK'),
  ('Dumbbell Goblet Reverse Lunge', 'https://youtu.be/pDA738FZsuk?si=bzG9vYvbc69IfMmO'),
  ('Dumbbell Goblet Russian Step Up', 'https://youtu.be/Z8wrpP7TT5E?si=tMWVlz_jrcW6ilLl'),
  ('Dumbbell Goblet Split Squat', 'https://youtu.be/EUHaKY3aA1Q?si=H2a-9iB71twMingb'),
  ('Dumbbell Goblet Squat', 'https://youtu.be/a-dqF4NL2K4'),
  ('Dumbbell Goblet Step Up', 'https://youtu.be/PLk0TE6nYag?si=vbbSLrl8kCSWEbLQ'),
  ('Dumbbell Goblet Walking Lunge', 'https://youtu.be/gA6gJS2ePGU?si=Ug9x4DfIITtyX9FE'),
  ('Dumbbell Hip Thrust', 'https://youtu.be/LxdfGyNBuRU?si=x25Sk4tkkLiyY4t2'),
  ('Dumbbell Incline Bench Pullover', 'https://youtu.be/LQEag7MKXSs?si=vVcujNN4QVFLQ71H'),
  ('Dumbbell Low Hold Cossack Squat', 'https://youtu.be/k4p89WEkl58?si=S4JsgnfzWmFK3l4G'),
  ('Dumbbell Pullover', 'https://youtu.be/owr5y-s6-Qk?si=gd2Nfg1PVMbahXjx'),
  ('EZ Bar Reverse Grip Bent Over Row', 'https://youtu.be/mq_KoN3oCgo?si=zVWL6owtdpddPPFb'),
  ('Kettlebell Dead Bug', 'https://youtu.be/pXcG0IH2Nkg'),
  ('Kettlebell Feet Elevated Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Kettlebell Frog Pump', 'https://youtu.be/cdvQmb5iNdc?si=WU6MMMqGPXHZwOf9'),
  ('Kettlebell Goblet Alternating Cossack Squat', 'https://youtu.be/wrYqfSLWqdE'),
  ('Kettlebell Goblet Alternating Curtsy Lunge', 'https://youtu.be/dj2zCtnlZEM?si=zXmmDlSwlhudznYC'),
  ('Kettlebell Goblet Alternating Forward Lunge', 'https://youtu.be/wkMhmQ5wVWY?si=kFZCkvoaBfUNdjvU'),
  ('Kettlebell Goblet Alternating Lateral Lunge', 'https://youtu.be/Z8dcGhS8giQ?si=iQZ35AJwvoHewxyk'),
  ('Kettlebell Goblet Alternating Reverse Lunge', 'https://youtu.be/Q8s5KVgRjsI?si=LU2DAUzkwtjOm87N'),
  ('Kettlebell Goblet Alternating Russian Step Up', 'https://youtu.be/D_XZAV9sh2I?si=9d58XpgxLS_aoYoQ'),
  ('Kettlebell Goblet Alternating Step Up', 'https://youtu.be/uT2473eo8Rw?si=1pxHtkIQiIW_apsw'),
  ('Kettlebell Goblet Carry', 'https://youtu.be/PN8ATPtOYEE?si=zcjMbUMXIWHgX7E_'),
  ('Kettlebell Goblet Curtsy Lunge', 'https://youtu.be/863JuZlLiA4?si=Zj6W2E1ana1MwTBv'),
  ('Kettlebell Goblet Cyclist Squat', 'https://youtu.be/JMGY7iOxEd8?si=VQLmn1jf71I47o_a'),
  ('Kettlebell Goblet Foot Elevated Cossack Squat', 'https://youtu.be/fhkFo0BxF5k'),
  ('Kettlebell Goblet Foot Elevated Knee Over Toe Split Squat', 'https://youtu.be/JGpJCYbDefo?si=NOFTsBroAKhZtrMl'),
  ('Kettlebell Goblet Forward Lunge', 'https://youtu.be/5zdsUZyVyZU?si=zOn7HfTe53mopVx9'),
  ('Kettlebell Goblet Horse Stance Squat', 'https://youtu.be/ZZ1piVHgy_8?si=I9HrW8xbkLx_UyJS'),
  ('Kettlebell Goblet Knee Over Toe Split Squat', 'https://youtu.be/9b4Aatm0Wvo?si=35ADJVaHZbeshP13'),
  ('Kettlebell Goblet Lateral Lunge', 'https://youtu.be/kLdLvTsVbeU?si=ncvaPkFaqqmfK76j'),
  ('Kettlebell Goblet Reverse Lunge', 'https://youtu.be/s5w0EOsU7e8?si=UCHj4c3UE1LScgnx'),
  ('Kettlebell Goblet Russian Step Up', 'https://youtu.be/RZsegx5MjMg?si=jrgTO3B_RBqc2Tow'),
  ('Kettlebell Goblet Split Squat', 'https://youtu.be/X13mW_a88Hw?si=bAwJPsrYMO6xCJWC'),
  ('Kettlebell Goblet Squat', 'https://youtu.be/f-Vf2yRRqOg'),
  ('Kettlebell Goblet Step Up', 'https://youtu.be/ci0s9-U1S50?si=yYac1epKRR8CESOn'),
  ('Kettlebell Goblet Walking Lunge', 'https://youtu.be/oV97EckMQlo?si=-UB0G60JaIQ6f-4v'),
  ('Kettlebell Horn Grip Alternating Cossack Squat', 'https://youtu.be/VFFS9y4czO8?si=iICpgUIx3HuQxAXK'),
  ('Kettlebell Horn Grip Alternating Curtsy Lunge', 'https://youtu.be/0xnBB7_WBpQ?si=DNO9eiIOlnVvq62-'),
  ('Kettlebell Horn Grip Alternating Forward Lunge', 'https://youtu.be/fZeR04SyMnM?si=PcC3GMitpRy-d_N5'),
  ('Kettlebell Horn Grip Alternating Lateral Lunge', 'https://youtu.be/hP0wET7bCog?si=trU9Rde7VACKCuEn'),
  ('Kettlebell Horn Grip Alternating Reverse Lunge', 'https://youtu.be/hn0H9wrT7I0?si=2puOZbS5dzRQTGh6'),
  ('Kettlebell Horn Grip Alternating Step Up', 'https://youtu.be/moDnqcjmUnw?si=2L_tGgiIN_WKjnSh'),
  ('Kettlebell Horn Grip Carry', 'https://youtu.be/LcF_derN9KA?si=U_Cqiq6zxtQlpRhf'),
  ('Kettlebell Horn Grip Cossack Squat', 'https://youtu.be/rSaWYv37zzE?si=A1Q8ZZrV4BpY2YTj'),
  ('Kettlebell Horn Grip Curtsy Lunge', 'https://youtu.be/sb9anlSqH6w?feature=shared'),
  ('Kettlebell Horn Grip Cyclist Squat', 'https://youtu.be/TysYZ7rKhpM'),
  ('Kettlebell Horn Grip Foot Elevated Cossack Squat', 'https://youtu.be/m7SpIGBcysg?feature=shared'),
  ('Kettlebell Horn Grip Forward Lunge', 'https://youtu.be/B2jHsaojI4A?si=t3FbVaw_mjK5VgeG'),
  ('Kettlebell Horn Grip Lateral Lunge', 'https://youtu.be/rWKbV7s0bhc?si=DBfnajIIdfbAlzNg'),
  ('Kettlebell Horn Grip Reverse Lunge', 'https://youtu.be/gWN9epxFqX8?si=h3iRgeFCZgBGHOMT'),
  ('Kettlebell Horn Grip Split Squat', 'https://youtu.be/OjBghWkudHk?si=LxwZc1KnuyA20kv-'),
  ('Kettlebell Horn Grip Squat', 'https://youtu.be/1Yw4YA4cwAo?si=fX6SXG6cfeXhhNQ_'),
  ('Kettlebell Horn Grip Step Up', 'https://youtu.be/ciJ8vZIyapM?si=F5Cq1A6IBA0ElWWo'),
  ('Kettlebell Horn Grip Walking Lunge', 'https://youtu.be/d7cVOMtyjS8?si=-LwL939gyb_zs3lu'),
  ('Kettlebell Low Hold Alternating Cossack Squat', 'https://youtu.be/ZclBW2lK-lY?si=fR_4w2NKvW_BzggV'),
  ('Kettlebell Low Hold Alternating Lateral Lunge', 'https://youtu.be/w6vfiCgfbXA?si=RhaJhv_PYjW4LLj5'),
  ('Kettlebell Low Hold Cossack Squat', 'https://youtu.be/svU3rff73Mo?si=wBPTEMnydOoIKHgd'),
  ('Kettlebell Romanian Deadlift', 'https://youtu.be/keiZFdUgvKQ?si=dkMliNkbyV8fodl2'),
  ('Kettlebell Russian Twist', 'https://youtu.be/59_aq7COfts'),
  ('Kettlebell Start Stop Swing', 'https://youtu.be/cZSh_cYNXTw'),
  ('Kettlebell Sumo Deadlift', 'https://youtu.be/odS65TnXgU0?si=l3QM9Nb4wHNt_JgK'),
  ('Kettlebell Swing', 'https://youtu.be/1cVT3ee9mgU'),
  ('Landmine Goblet Alternating Lateral Lunge', 'https://youtu.be/-hWgE1P2aAA?si=7mOaE_-aBxpQNBSX'),
  ('Landmine Goblet Alternating Reverse Lunge', 'https://youtu.be/VI0GDe_doBk?si=U14f8Dk6Ly1aMzBr'),
  ('Landmine Goblet Cyclist Squat', 'https://youtu.be/MeBEmS3QRjE?si=lZ0o-kYlVdKtkDqe'),
  ('Landmine Goblet Split Squat', 'https://youtu.be/IfR7ezW6Oxc?si=-Zb29PMa_gZ8yJr9'),
  ('Landmine Goblet Squat', 'https://youtu.be/oTRl7p13XtY'),
  ('Landmine Low Hold Lateral Lunge', 'https://youtu.be/VTtLrBvHoJ8'),
  ('Landmine Romanian Deadlift', 'https://youtu.be/x5wWyQ-2k2E?feature=shared'),
  ('Landmine Russian Twist', 'https://youtu.be/OyKu-DvXxAc?feature=shared'),
  ('Landmine Thruster', 'https://youtu.be/jLvQenjeus8'),
  ('Landmine V Grip Row', 'https://youtu.be/gnikveF7dgI'),
  ('Macebell Barbarian Squat', 'https://youtu.be/Gj3ancpDFKU?si=TKfk3RmqTwztmb1j'),
  ('Macebell Offset Bent Over Row', 'https://youtu.be/OXl94TQd_vw?si=AMXpvOM-H382GJoz'),
  ('Macebell Reverse Grip Offset Bent Over Row', 'https://youtu.be/igNnqZZ69JM?si=xaqrnAFrW4r7NuVR'),
  ('Medicine Ball Alternating Single Leg V Up', 'https://youtu.be/Pp32aIWX-XQ?si=nbvgHN2LwSgXB904'),
  ('Medicine Ball Feet Elevated Russian Twist', 'https://youtu.be/IdEocZzdUNY'),
  ('Medicine Ball Otis Up', 'https://youtu.be/b-06cnxJ2YY?si=wCCcWK7wyR8RgwCV'),
  ('Medicine Ball Russian Twist', 'https://youtu.be/vT8p57mXVDo?feature=shared'),
  ('Medicine Ball V Up', 'https://youtu.be/E0WFCTnN728?si=YvTVZvOCRm_hjh2B'),
  ('Miniband 3 Way Cha Cha', 'https://youtu.be/3SOcMYQWbDU'),
  ('Miniband Ankle Lateral Walk', 'https://youtu.be/N4tkpDMlqCQ'),
  ('Miniband Ankle Monster Walk', 'https://youtu.be/PlktrKgFcT0?si=O4YEDtcE-rMg5fLn'),
  ('Miniband Ankle Side Lying Hip Abduction', 'https://youtu.be/bDvFd4EZt8M'),
  ('Miniband Bench Seated Hip Abduction', 'https://youtu.be/NeO0w4Jv4rs?si=zFKHnPvts0-arQgk'),
  ('Miniband Bicycle Crunch', 'https://youtu.be/q_c5MFYuza4'),
  ('Miniband Dead Bug', 'https://youtu.be/hSVxpNktAZ4?si=X2QXPPV90G-NjXyx'),
  ('Miniband Feet Elevated Frog Pump', 'https://youtu.be/B1brbzxGCqM?si=OdHzF3vTHn2YmADJ'),
  ('Miniband Feet Elevated Glute Bridge', 'https://youtu.be/hKUOvDXVREw?si=RIjR5zIo0hOuYfY0'),
  ('Miniband Fire Hydrant', 'https://youtu.be/gnzypKUFU6Y'),
  ('Miniband Frog Pump', 'https://youtu.be/rzjQ8XpXt1Q'),
  ('Miniband Glute Bridge', 'https://youtu.be/Zr2RLjIjCN0?si=CFxCFwgSlgd_2sCv'),
  ('Miniband Glute Bridge Hip Abduction', 'https://youtu.be/oS3cYfl6Bns'),
  ('Miniband Hip Thrust', 'https://youtu.be/GMoIkfo2nP4?si=IB4Q_47E137Hsx_H'),
  ('Miniband Kneeling Side Plank Clamshell', 'https://youtu.be/DD2ntrZLoEQ?feature=shared'),
  ('Miniband Quadruped Hip Extension', 'https://youtu.be/k30hN0vhlsY?si=ycYwNbMrFEnA94pG'),
  ('Miniband Romanian Deadlift', 'https://youtu.be/N5lBa2zMAPI?si=Eth4HWtKMOXBXNx6'),
  ('Miniband Side Lying Clamshell', 'https://youtu.be/vSpyJR3dA7s?si=voo83Swm5kMbYEwl'),
  ('Miniband Single Leg Hip Thrust', 'https://youtu.be/tPWyj85zsmg'),
  ('Miniband Standing Glute Kickback', 'https://youtu.be/pdP0uJXvc44?si=lpmJ6krZopavsZrJ'),
  ('Miniband Standing Hip Abduction', 'https://youtu.be/dZNkjqKNUUs'),
  ('Miniband Thigh In and Out Squat Jump', 'https://youtu.be/cguZ74v0_bE?si=wU22GaKrEc-GA4sw'),
  ('Miniband Thigh Kneeling Side Plank Hip Abduction', 'https://youtu.be/RrL3tkrRefw?feature=shared'),
  ('Miniband Thigh Lateral Walk', 'https://youtu.be/34fVGXqWWs8'),
  ('Miniband Thigh Monster Walk', 'https://youtu.be/po3I8qoRC2c?si=XeJ7Tq5PXt3WLJfl'),
  ('Miniband Thigh Side Plank Hip Abduction', 'https://youtu.be/TBYwwlojtvE?si=QWpnXUtKvTpFNuv_'),
  ('Miniband Wall Sit Hip Abduction', 'https://youtu.be/w5nYnnT1E9s'),
  ('Parallette Mountain Climber', 'https://youtu.be/W0RoAqlFzrA'),
  ('Parallette Plank', 'https://youtu.be/MP6yL_KKxYY?si=Q87bAjMVT-uTdGRq'),
  ('Plate Dead Bug', 'https://youtu.be/DPNDaQoxjsQ?si=KOvphYYrIaszuK1F'),
  ('Plate Feet Elevated Russian Twist', 'https://youtu.be/4p5jWyz-YRQ?si=A80S2QY5Wu5Lql2-'),
  ('Plate Hip Thrust', 'https://youtu.be/k_HORfTCsi0?si=-RDu4SzCjbkXl4P5'),
  ('Plate Otis Up', 'https://youtu.be/vjAjAERSkIk'),
  ('Plate Russian Twist', 'https://youtu.be/JYftrLVWUD8?si=WwaPZ7K8HUnsrnqN'),
  ('Plate Side Lying Bent Knee Hip Abduction', 'https://youtu.be/jpxdm8SJ5wM?si=35jEMaJ1JRWnO1ET'),
  ('Resistance Band Low Row', 'https://youtu.be/wRLkttcydwo?si=F9hMpgbV2W-oo3W5'),
  ('Resistance Band Mid Row', 'https://youtu.be/mdf7cMhqRqs?si=P_AYp9PgEajEP_il'),
  ('Ring Body Saw', 'https://youtu.be/EqGVH1qHzwU?si=hyDFD2YkFH9OLT29'),
  ('Ring Bulgarian Row', 'https://youtu.be/5CxPrNkhm2k'),
  ('Ring Eccentric Pull Up', 'https://youtu.be/4vEoBieXyKk'),
  ('Ring Plank', 'https://youtu.be/p3zS2AMqGlg'),
  ('Ring Row', 'https://youtu.be/xhlReCpAE9k'),
  ('Sandbag Back Rack Alternating Cossack Squat', 'https://youtu.be/V-CvLcQhsPk?feature=shared'),
  ('Sandbag Back Rack Alternating Curtsy Lunge', 'https://youtu.be/L6KZyggcDjE?feature=shared'),
  ('Sandbag Back Rack Bulgarian Split Squat', 'https://youtu.be/uuVkmAJd-y0?si=JvCPYFXj-MAzRMAF'),
  ('Sandbag Back Rack Split Squat', 'https://youtu.be/h1IDfUy9JCg?si=8aLbq-QZwId9tfAE'),
  ('Sandbag Back Rack Squat', 'https://youtu.be/TTZlek-Jeec?si=nJsuOnJws7uylodj'),
  ('Sandbag Back Rack Walking Lunge', 'https://youtu.be/LUESjt8b2vY?si=vYksLJ6mIw7_F_DZ'),
  ('Sandbag Bent Over Row', 'https://youtu.be/QWniDREaQVY?si=nOmYsg0t5nXPcb0Q'),
  ('Sandbag Front Rack Alternating Cossack Squat', 'https://youtu.be/XOCZvsIB-ys?si=icJ1C2ots-yLy5_7'),
  ('Sandbag Front Rack Alternating Forward Lunge', 'https://youtu.be/1L2HnCKmsRs?si=fIVyc7oXYDkkRzgJ'),
  ('Sandbag Front Rack Alternating Lateral Lunge', 'https://youtu.be/0el8H9fy3g0?si=BdlZ75xoh6Xq1wpJ'),
  ('Sandbag Front Rack Alternating Reverse Lunge', 'https://youtu.be/SJe_O4NPU-E?si=OKoj1OGsurlSWTEA'),
  ('Sandbag Front Rack Bulgarian Split Squat', 'https://youtu.be/41RTZolbtPk?si=HjTttPYPllgpQXeT'),
  ('Sandbag Front Rack Curtsy Lunge', 'https://youtu.be/2DiU1YRLDQE?si=klXwkCZb6RsZjZl5'),
  ('Sandbag Front Rack Forward Lunge', 'https://youtu.be/DoXtPhcQZ0A?si=-jOVMkwU4yMda8b5'),
  ('Sandbag Front Rack Lateral Lunge', 'https://youtu.be/U-z_jIM8Tew?si=SZspUD2oLZXeO5D2'),
  ('Sandbag Front Rack Reverse Lunge', 'https://youtu.be/I9YUnFtd81o?si=yuqTt95kbjtVETJd'),
  ('Sandbag Front Rack Split Squat', 'https://youtu.be/b0rzm8OUjAc?si=Rz4zXBOgcisU6tEb'),
  ('Sandbag Front Rack Squat', 'https://youtu.be/-TTZd1lASkw?si=T4OTaFzbqRaGAc3m'),
  ('Sandbag Front Rack Walking Lunge', 'https://youtu.be/mGwXPP-QKko?si=pUfEZOZPOOYaTV3n'),
  ('Sandbag Thruster', 'https://youtu.be/Zw0q4TYy8eI?si=-MWyXSvjBoei8Mmn'),
  ('Single Arm Barbell Suitcase Deadlift', 'https://youtu.be/E7vYUfMcFhs?si=bti9p5lCqTpD-Y-q'),
  ('Single Arm Cable Half Kneeling Lat Pulldown', 'https://youtu.be/4QDCC2gU5_E'),
  ('Single Arm Cable Half Kneeling Low Row', 'https://youtu.be/redrpTwkplw'),
  ('Single Arm Cable Seated Floor Lat Pulldown', 'https://youtu.be/N7FcfA7UFZk'),
  ('Single Arm Cable Shotgun Row', 'https://youtu.be/91nVZ7FLPyA?si=_khiKXF3khjyeuSP'),
  ('Single Arm Clubbell Barbarian Squat', 'https://youtu.be/g1NRUDyqlH8?si=D2hTo9Ntck6F1dcx'),
  ('Single Arm Clubbell Inside Pullover', 'https://youtu.be/DQg80eX08hg?si=LmF-paCX4u8uFLO7'),
  ('Single Arm Clubbell Order Ipsilateral Forward Lunge', 'https://youtu.be/lBKvPGFLaKg?si=ysrtgn3hQImmLVaF'),
  ('Single Arm Clubbell Outside Pullover', 'https://youtu.be/sJ5XCgdCMx8?si=VIRgX4J73IavMF93'),
  ('Single Arm Clubbell Pullover', 'https://youtu.be/JJgOmmqZneM?si=v93qv5Poy03NJqj_'),
  ('Single Arm Dumbbell Bent Over Row', 'https://youtu.be/ma__uqUlYmE?si=Yw6Iw4KOA3T7mJeL'),
  ('Single Arm Dumbbell Cyclist Thruster', 'https://youtu.be/2Tt0XZ2pZyE'),
  ('Single Arm Dumbbell Front Rack Alternating Curtsy Lunge', 'https://youtu.be/lJyMP5H-_pw?feature=shared'),
  ('Single Arm Dumbbell Front Rack Alternating Forward Lunge', 'https://youtu.be/b3ewFBSqc9k?si=l6I7tV4HN4z6vcCS'),
  ('Single Arm Dumbbell Front Rack Alternating Reverse Lunge', 'https://youtu.be/1uuCmY9bVao?si=0iam54INq6LqKgrV'),
  ('Single Arm Dumbbell Front Rack Carry', 'https://youtu.be/5rsJK_z8nkY?si=CD5k3-b0r_JJpfHM'),
  ('Single Arm Dumbbell Front Rack Contralateral Cossack Squat', 'https://youtu.be/cmB4dq8MgVk?si=s0qFLxm2MDbbX3dw'),
  ('Single Arm Dumbbell Front Rack Contralateral Curtsy Lunge', 'https://youtu.be/6-K9hgU8YUI?si=eubdVXn2jNhff_kr'),
  ('Single Arm Dumbbell Front Rack Contralateral Forward Lunge', 'https://youtu.be/UbQwG3BPs54?si=OAD_X1vRpwmgJgHl'),
  ('Single Arm Dumbbell Front Rack Contralateral Lateral Lunge', 'https://youtu.be/OWIhh8vYl-M?si=WNuup7a0fJkVHgbd'),
  ('Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/d3oKvFQ2KOk?si=DHn68Kf7oX9vBrYU'),
  ('Single Arm Dumbbell Front Rack Contralateral Russian Step Up', 'https://youtu.be/ZrFBGqWoSzw?si=pCq_xiI6MtbnQOMx'),
  ('Single Arm Dumbbell Front Rack Contralateral Split Squat', 'https://youtu.be/nogkCbiduHI?si=5gA5NaZqt_y4a8ir'),
  ('Single Arm Dumbbell Front Rack Contralateral Step Up', 'https://youtu.be/KGBRsXKjWOc?si=RnQ_ABDo5MNzq0-i'),
  ('Single Arm Dumbbell Front Rack Cyclist Squat', 'https://youtu.be/eGKpS3AxCVA?si=-uyv4kyU-FY0yBfB'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Cossack Squat', 'https://youtu.be/S1-SPv3YXG8?si=QCE1ikc3-Mg60u3x'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Curtsy Lunge', 'https://youtu.be/yswpCMZ98OI?si=xOcXSLCrJIH3odmK'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Forward Lunge', 'https://youtu.be/hSqr6cDitEg?si=0Q3eJ7Civ09nXoAr'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Lateral Lunge', 'https://youtu.be/eKSHQsVMOK4?si=5Lej30jpx3r7UZJB'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Reverse Lunge', 'https://youtu.be/RxBzGBShf9w?si=yD5EyWT1k3UeODJI'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Russian Step Up', 'https://youtu.be/-4eThA6jaBY?si=rvYxSeDEierXbTvB'),
  ('Single Arm Dumbbell Front Rack Ipsilateral Split Squat', 'https://youtu.be/Fc6I5y692zE?si=WC2rmdrASF2eyb71'),
  ('Single Arm Dumbbell Front Rack Squat', 'https://youtu.be/1VzKnqCcUJ4'),
  ('Single Arm Dumbbell Front Rack Walking Lunge', 'https://youtu.be/GGjKBYEkZ-A?si=faI8XOKTHMInvAqG'),
  ('Single Arm Dumbbell Incline Bench Prone Row', 'https://youtu.be/4Bv94e_ufjo?si=8V5SPIIuNai7zUm3'),
  ('Single Arm Dumbbell Knee Supported Row', 'https://youtu.be/ZRSGpBUVcNw?si=x3MRv2xRNjCc6s42'),
  ('Single Arm Dumbbell Suitcase Alternating Forward Lunge', 'https://youtu.be/DbANzYj8EWQ?si=NULTCgfWBvm6vNpX'),
  ('Single Arm Dumbbell Suitcase Alternating Reverse Lunge', 'https://youtu.be/kTfl5mhcwso?si=iDo9iOmHhKSZIQlN'),
  ('Single Arm Dumbbell Suitcase Contralateral Curtsy Lunge', 'https://youtu.be/XSvx131FZ_s?feature=shared'),
  ('Single Arm Dumbbell Suitcase Contralateral Forward Lunge', 'https://youtu.be/nEFul0yIBzU?si=Dt-DKAqMcRsQMRWd'),
  ('Single Arm Dumbbell Suitcase Contralateral Lateral Lunge', 'https://youtu.be/-5W0Wi2_vps?feature=shared'),
  ('Single Arm Dumbbell Suitcase Contralateral Reverse Lunge', 'https://youtu.be/ZsmsBmOMtnw?si=FMtq9k1eAmHq4gEX'),
  ('Single Arm Dumbbell Suitcase Contralateral Russian Step Up', 'https://youtu.be/cB20h7IpdJQ?si=KBJR-jjHokOwHkYv'),
  ('Single Arm Dumbbell Suitcase Contralateral Split Squat', 'https://youtu.be/eT5ol-m5gQU?si=1yRDnXPgi913NC1Q'),
  ('Single Arm Dumbbell Suitcase Contralateral Step Up', 'https://youtu.be/23z9Mb4sMVk?feature=shared'),
  ('Single Arm Dumbbell Suitcase Deadlift', 'https://youtu.be/yMRbcOd51pA?si=7Hc1xBgOqKKuKw3C'),
  ('Single Arm Dumbbell Suitcase Foot Elevated Contralateral Knee Over Toe Split Squat', 'https://youtu.be/FpwomyrCcCk?si=JJyauhDa3bMzRSkq'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Curtsy Lunge', 'https://youtu.be/8lACiuIcv_0?feature=shared'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Forward Lunge', 'https://youtu.be/6qREgTKXbOM?si=gyM_F4WYjs2hqIS7'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Reverse Lunge', 'https://youtu.be/uzn966rWQ4c?si=XF_kMH6vfBIw4hz4'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Split Squat', 'https://youtu.be/PL3rLZbBgZQ?si=NevvL1vzasNBOgVT'),
  ('Single Arm Dumbbell Suitcase Ipsilateral Step Up', 'https://youtu.be/fWhOG_9eHdE?feature=shared'),
  ('Single Arm Dumbbell Suitcase Walking Lunge', 'https://youtu.be/QR1CViFqmmc?si=4Lxq-QIIZ55jvMdx'),
  ('Single Arm Dumbbell Thruster', 'https://youtu.be/03aX4h5-EkA'),
  ('Single Arm Kettlebell Around the World', 'https://youtu.be/6AzrdFj3Qfc?si=52vAx7-XXfvkSz_l'),
  ('Single Arm Kettlebell Bent Over Row', 'https://youtu.be/9Q9gwoXHn1o'),
  ('Single Arm Kettlebell Front Rack Alternating Cossack Squat', 'https://youtu.be/JqoC2gQ1MRE'),
  ('Single Arm Kettlebell Front Rack Alternating Forward Lunge', 'https://youtu.be/oOB02xJgzrA?si=IO-ooFFstcNesTGD'),
  ('Single Arm Kettlebell Front Rack Alternating Lateral Lunge', 'https://youtu.be/vVElqek25fI?si=4-FGE3vFSRTkYdG4'),
  ('Single Arm Kettlebell Front Rack Alternating Reverse Lunge', 'https://youtu.be/tildBryP8bI?si=mIky-m7uqR4kMvB3'),
  ('Single Arm Kettlebell Front Rack Carry', 'https://youtu.be/M39871Puz6c'),
  ('Single Arm Kettlebell Front Rack Contralateral Cossack Squat', 'https://youtu.be/4NCYLWTv5Mc?si=OT9LNGr9wS3RbezC'),
  ('Single Arm Kettlebell Front Rack Contralateral Curtsy Lunge', 'https://youtu.be/XVsdDBiLk2I?si=yYz392PvLdjJCOy5'),
  ('Single Arm Kettlebell Front Rack Contralateral Forward Lunge', 'https://youtu.be/93jOACk6hCI?si=Wh87FQShHz6PdDPL'),
  ('Single Arm Kettlebell Front Rack Contralateral Lateral Lunge', 'https://youtu.be/Zsabw1IsO9I?si=b5LVn94BLkSHKB_5'),
  ('Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/kcVqtqe03WI?si=KuFsD1PlWdph7WCt'),
  ('Single Arm Kettlebell Front Rack Contralateral Russian Step Up', 'https://youtu.be/nijhpzgUUi0?si=OYbqhyHxgBZEG3ZY'),
  ('Single Arm Kettlebell Front Rack Contralateral Split Squat', 'https://youtu.be/-Z8NXAi59SE'),
  ('Single Arm Kettlebell Front Rack Cyclist Squat', 'https://youtu.be/_FjMUe0AhTY'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Cossack Squat', 'https://youtu.be/AYgBothlkOA?si=hiSrcI8KbslXlQrq'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Curtsy Lunge', 'https://youtu.be/dwL1uWmadTI?si=6anEQDI0eEoOuB0Q'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Forward Lunge', 'https://youtu.be/vnwL74DnWK8?si=qsKdUhrsdu46i1An'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'https://youtu.be/r1NS0BNUh3c?si=XwpKqEi6aUMJvPq5'),
  ('Single Arm Kettlebell Front Rack Ipsilateral Split Squat', 'https://youtu.be/Xy9DrXmYIdw?si=e3qLZQjQ9a0RnC4q'),
  ('Single Arm Kettlebell Front Rack Squat', 'https://youtu.be/Wqg4NY5XAkU'),
  ('Single Arm Kettlebell Front Rack Walking Lunge', 'https://youtu.be/9C-hKwyOaE4?si=SpYmw0aHIO29g-Cj'),
  ('Single Arm Kettlebell Incline Bench Prone Row', 'https://youtu.be/gPX8OmnYmQY?si=UgQnJkh9n3OobTcZ'),
  ('Single Arm Kettlebell Knee Supported Row', 'https://youtu.be/JdXRG8B3N8E?si=uO1aFa0IBUO3nVqz'),
  ('Single Arm Kettlebell Outside Swing', 'https://youtu.be/sEerteQ9q8Y?si=eO7tUCscpuCkcIez'),
  ('Single Arm Kettlebell Pendlay Row', 'https://youtu.be/VOmnhGvccZ0?feature=shared'),
  ('Single Arm Kettlebell Prone Row', 'https://youtu.be/QSbH7gNkBtc?si=ngxTS90XoTuvQDxs'),
  ('Single Arm Kettlebell Rotational Thruster', 'https://youtu.be/jkbJFWzllH4'),
  ('Single Arm Kettlebell Start Stop Swing', 'https://youtu.be/djCYBs70KLE?si=JiYJei8Eqv-UiCG7'),
  ('Single Arm Kettlebell Suitcase Alternating Forward Lunge', 'https://youtu.be/aopAoW1cmUk?si=EyVEsJC9bLaQC6ND'),
  ('Single Arm Kettlebell Suitcase Alternating Reverse Lunge', 'https://youtu.be/CQR7UUijw38?si=ncO4L8hVq2h4htQQ'),
  ('Single Arm Kettlebell Suitcase Contralateral Curtsy Lunge', 'https://youtu.be/IlABYRygo3w?si=LYId2yiYvpqxybEC'),
  ('Single Arm Kettlebell Suitcase Contralateral Knee Over Toe Split Squat', 'https://youtu.be/eGYP6B7LKtY?si=OkQLiBCrooH2qA67'),
  ('Single Arm Kettlebell Suitcase Contralateral Lateral Lunge', 'https://youtu.be/NlkYG2ZJ0OE?si=oa1-NGoydk-xKSsq'),
  ('Single Arm Kettlebell Suitcase Contralateral Reverse Lunge', 'https://youtu.be/rwlsbVNSqDQ?si=6ELRzgo6Ek1bVGBe'),
  ('Single Arm Kettlebell Suitcase Contralateral Split Squat', 'https://youtu.be/JLyFg72CCrk?si=dyii9fe_jm4Th1O8'),
  ('Single Arm Kettlebell Suitcase Contralateral Step Up', 'https://youtu.be/lMADALbx1eM?si=wJjWrYeLHPKqVgHh'),
  ('Single Arm Kettlebell Suitcase Cyclist Squat', 'https://youtu.be/AlxuA22ymwg?si=-tgz7djxN0QKxXfA'),
  ('Single Arm Kettlebell Suitcase Deadlift', 'https://youtu.be/1hcAoywwuRI'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Forward Lunge', 'https://youtu.be/TPCs1UFpADo?si=m8DKfTmxHGcavJDM'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'https://youtu.be/Ae33oITfYwM?si=BTB-LZkHb2SHl8HM'),
  ('Single Arm Kettlebell Suitcase Ipsilateral Split Squat', 'https://youtu.be/ZqPQvlALHlw?si=B7EklAroPtpJvXvc'),
  ('Single Arm Kettlebell Suitcase Walking Lunge', 'https://youtu.be/ojCvehn5SjY?si=tdD_tXPCt_VXy9h3'),
  ('Single Arm Kettlebell Sumo Deadlift', 'https://youtu.be/1XyV5eNL1z0'),
  ('Single Arm Kettlebell Swing', 'https://youtu.be/kneGICiz30g'),
  ('Single Arm Kettlebell Tall Kneeling Around the World', 'https://youtu.be/9vZ0CU0dHcE'),
  ('Single Arm Landmine Front Rack Contralateral Split Squat', 'https://youtu.be/kZKDLL-1IXw?si=wnx7XbsDFO37wHb3'),
  ('Single Arm Landmine Meadows Row', 'https://youtu.be/e-c4gMcqdyw'),
  ('Single Arm Landmine Row', 'https://youtu.be/tiETx7VNDf0'),
  ('Single Arm Landmine Suitcase Contralateral Split Squat', 'https://youtu.be/rD7QCqe4g0k?si=13maugTiL5P1XI6m'),
  ('Single Arm Resistance Band Low Row', 'https://youtu.be/apYOwiF9moM?si=bOCR3Ldpx6nSTzj0'),
  ('Single Arm Suspension Cyclist Squat', 'https://youtu.be/wkgihbMp6BY?si=uztwb4emdctDZXbe'),
  ('Single Arm Suspension Ipsilateral Cossack Squat', 'https://youtu.be/8xX1a7o6bKU?si=rLYvcvZkeDzk1KV5'),
  ('Single Arm Suspension Low Row', 'https://youtu.be/wH4TXGV8UyA?si=N8Y8Uk0A9glEeeuQ'),
  ('Slam Ball Overhead Slam', 'https://youtu.be/k9W6g9LvXDI?si=r2ny_BUMtle93fEw'),
  ('Slam Ball Russian Twist', 'https://youtu.be/qyZ0pAtgo_Y'),
  ('Slam Ball Tall Kneeling Overhead Slam', 'https://youtu.be/LhCS360FBvA?si=NOWK4R-Br_tSVldj'),
  ('Slider Body Saw', 'https://youtu.be/cC3nItw-szY?si=-UBQr2PgbT6bRuKh&utm_source=MTQxZ'),
  ('Slider Curtsy Lunge', 'https://youtu.be/3psxN3YA0wg?si=BW-ePbc5Pg6OJ8z6'),
  ('Slider Double Dumbbell Front Rack Lateral Lunge', 'https://youtu.be/EgG51yB1uZU?si=2CM1EcrBstAp5uOM'),
  ('Slider Double Dumbbell Front Rack Reverse Lunge', 'https://youtu.be/RoS53TjR2QY?si=6bemyT1DeK6D_ziA'),
  ('Slider Double Dumbbell Suitcase Lateral Lunge', 'https://youtu.be/90Smo-K6RbY?si=kkqWO4ejlGrcq6rR'),
  ('Slider Double Dumbbell Suitcase Reverse Lunge', 'https://youtu.be/jo1G9aygVIY?si=rDCyU7nAR0DQrhQr'),
  ('Slider Double Kettlebell Front Rack Reverse Lunge', 'https://youtu.be/-p1l0vXTtAU?si=ebEJZJZkoWYTDFbC'),
  ('Slider Double Kettlebell Suitcase Lateral Lunge', 'https://youtu.be/bAaaXP2xb8E?si=AOaxE4RzaGKjiq0h'),
  ('Slider Double Kettlebell Suitcase Reverse Lunge', 'https://youtu.be/1SlpUMsiiiw?si=WnEVv0WTROHdU4eR'),
  ('Slider Dumbbell Goblet Curtsy Lunge', 'https://youtu.be/lyYXfpCV5ys?si=iACRC6Vlz_wbm5zc'),
  ('Slider Dumbbell Goblet Lateral Lunge', 'https://youtu.be/bN9sXaI7tdg?si=W3RoLGE6wUeZ8kQg'),
  ('Slider Dumbbell Goblet Reverse Lunge', 'https://youtu.be/tWmzgpoOUls?si=Fmrp6-y_e5qk2SNJ'),
  ('Slider Eccentric Hamstring Curl', 'https://youtu.be/vcCVej7p_vc'),
  ('Slider Hamstring Curl', 'https://youtu.be/UaecXxAgsKA'),
  ('Slider Kettlebell Goblet Reverse Lunge', 'https://youtu.be/8k08cvYq-n8?si=bbPqV1XKB99kPfpP'),
  ('Slider Kettlebell Horn Grip Lateral Lunge', 'https://youtu.be/OsP6_mqxBDI?si=Kdp1ECOmqjUFcNM9'),
  ('Slider Kettlebell Horn Grip Reverse Lunge', 'https://youtu.be/wRgS5ObhBdQ?si=jFFxWIOs9ZRlGwqN'),
  ('Slider Knee Tuck', 'https://youtu.be/vx9j9l18pyE?si=U7boXKing8U74cQZ'),
  ('Slider Lateral Lunge', 'https://youtu.be/Gj12f62lLeM?si=VhTsZJu7DxtPvx73'),
  ('Slider Mountain Climber', 'https://youtu.be/fjHQIVIPLHY'),
  ('Slider Parallette Knee Tuck', 'https://youtu.be/Kj89v76f-l8?si=_B0Uc1Xs1x1S0G_M'),
  ('Slider Parallette Mountain Climber', 'https://youtu.be/lmtz6T204No?si=jbae97NKFny9b463'),
  ('Slider Plank Jack', 'https://youtu.be/lM33VtF6SCg?si=JG_kyBmQ8H-MspnB&utm_source=MTQxZ'),
  ('Slider Reverse Lunge', 'https://youtu.be/X9swqObTGJw?si=Qpxrkq0cR0xf5eiU'),
  ('Slider Sandbag Back Rack Lateral Lunge', 'https://youtu.be/GkANtw3THOg?si=LWzQCihOFKfrRvJz'),
  ('Slider Single Arm Dumbbell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/t8OkcdLjRFQ'),
  ('Slider Single Arm Dumbbell Low Hold Contralateral Lateral Lunge', 'https://youtu.be/QJ_WNRYaM-s?feature=shared'),
  ('Slider Single Arm Dumbbell Suitcase Contralateral Reverse Lunge', 'https://youtu.be/MAiTY-4x82Q?si=zKIXO7qWRH9Fp9yh'),
  ('Slider Single Arm Kettlebell Front Rack Contralateral Reverse Lunge', 'https://youtu.be/iRHrBseKm0k?si=X-TqbB38SGkCSqnE'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Lateral Lunge', 'https://youtu.be/q56KJzFPbz4?si=QBb7bgZdSeYK7Q0i'),
  ('Slider Single Arm Kettlebell Front Rack Ipsilateral Reverse Lunge', 'https://youtu.be/7wCLqLLyHh0?si=hFc7L_yPlG-KnZVg'),
  ('Slider Single Arm Kettlebell Low Hold Contralateral Lateral Lunge', 'https://youtu.be/W22ESpzYHdY?si=Vh4542ktziwY39x1'),
  ('Slider Single Arm Kettlebell Suitcase Contralateral Curtsy Lunge', 'https://youtu.be/Bu50PXycHv8?si=SlReQTpVRUbKnVsC'),
  ('Slider Single Arm Kettlebell Suitcase Contralateral Reverse Lunge', 'https://youtu.be/5D-hSAvpFls?si=2EfexeMUADw51Wu2'),
  ('Slider Single Arm Kettlebell Suitcase Ipsilateral Reverse Lunge', 'https://youtu.be/DS-pvuh8VEo?si=KEDC31EUxCubFjGj'),
  ('Slider Single Arm Landmine Suitcase Contralateral Reverse Lunge', 'https://youtu.be/XUrqwdRtU54?si=i9PTTagf_EVKwx0j'),
  ('Stability Ball Bent Knee Reverse Hyperextension', 'https://youtu.be/UOtzPdmg2Ow'),
  ('Stability Ball Body Saw', 'https://youtu.be/fgP2oii-GiQ?si=mbhNYj3pW612wBRY'),
  ('Stability Ball Cable Russian Twist', 'https://youtu.be/4ESBjh2BcdE'),
  ('Stability Ball Crunch', 'https://youtu.be/O4d3kd1ZLyc?si=xAr_I7jNLwrDm7lL'),
  ('Stability Ball Dead Bug', 'https://youtu.be/5jDEulwWs04'),
  ('Stability Ball Dumbbell Hip Thrust', 'https://youtu.be/x4lc8HocO1c'),
  ('Stability Ball Dumbbell Pullover', 'https://youtu.be/TI1gb3GFUVA'),
  ('Stability Ball Feet Elevated Crunch', 'https://youtu.be/ByXVlY2L3nw'),
  ('Stability Ball Feet Elevated Frog Pump', 'https://youtu.be/Rc5e-DsD--M'),
  ('Stability Ball Feet Elevated Glute Bridge', 'https://youtu.be/8Ta_A9vAEGs?si=pSj3gDFijzwcALE4'),
  ('Stability Ball Feet Elevated Oblique Crunch', 'https://youtu.be/fZZK29dMla0?si=BQpGveG4S8WqLjzv'),
  ('Stability Ball Feet Elevated Plank', 'https://youtu.be/MepSU7ua6Dw?si=wDktIQCYf3BtFlRS&utm_source=MTQxZ'),
  ('Stability Ball Feet Elevated Russian Twist', 'https://youtu.be/gyTX0ttszBs?si=mR6_J7SkVOuRHrQN'),
  ('Stability Ball Forearm Plank', 'https://youtu.be/4xODTD0UL-o?si=TSlUT4Fa309FslEb'),
  ('Stability Ball Frog Reverse Hyperextension', 'https://youtu.be/iiQueNJKmVQ?si=Ty5Dh9uswMacl2Jd'),
  ('Stability Ball Hamstring Curl', 'https://youtu.be/d-FBclT8W0g?si=wl1sJCzk2Z5PCnwx'),
  ('Stability Ball Hip Thrust', 'https://youtu.be/4azLK_5vOqY?si=bceKCFzhvhSW5jXe'),
  ('Stability Ball Hyperextension', 'https://youtu.be/bmRTtzOOiVM'),
  ('Stability Ball Knee Tuck', 'https://youtu.be/Q8MnsYG5sbk?si=8Aln2doES1PVTKQP'),
  ('Stability Ball Kneeling Body Saw', 'https://youtu.be/pYy3IaD55OM?si=zoWOIZ-SmoJywASH'),
  ('Stability Ball Kneeling Rollout', 'https://youtu.be/gi38qGKDzXY?si=XCqiGVtu482eeeTP'),
  ('Stability Ball Kneeling Stir the Pot', 'https://youtu.be/GMbT_cHg0dU?si=cnXGlMZAT5YjS73B'),
  ('Stability Ball Oblique Crunch', 'https://youtu.be/1gC-nI0XuZU'),
  ('Stability Ball Prone Cobra', 'https://youtu.be/qt1WWg8QDg8?si=Go7eAWcyWu13yBIi'),
  ('Stability Ball Reverse Crunch', 'https://youtu.be/duhPBZkq0xg?si=K4QIb8cjoQDdU-dJ'),
  ('Stability Ball Reverse Hyperextension', 'https://youtu.be/ujcZZ0kLEmY?si=Vb7GDY3_NgNICWqW'),
  ('Stability Ball Russian Twist', 'https://youtu.be/2rbbUJR-Nx4?si=aAPlfM1RYBeErvZk'),
  ('Stability Ball Single Leg Hip Thrust', 'https://youtu.be/p2Z02O1M18w?feature=shared'),
  ('Stability Ball Sit Up', 'https://youtu.be/7L90imlW0es?si=gY7k7XVC43IRrv-N'),
  ('Stability Ball Stir the Pot', 'https://youtu.be/IfOtFv6zz8I'),
  ('Stability Ball V Up Pass', 'https://youtu.be/n4UPDi5BuL0'),
  ('Stability Ball Wall Slide Squat', 'https://youtu.be/lWJ6BujsDYY?si=Hl4kTZutf9b6tDUi'),
  ('Stability Ball Windshield Wiper', 'https://youtu.be/tVfP2_HkXEc'),
  ('Superband Assisted Bar Pull Up', 'https://youtu.be/__TzXC-Hc_4?si=Z59SDF6EfXOY4pa_'),
  ('Superband Assisted Reverse Nordic', 'https://youtu.be/GHI2nT9CchQ?feature=shared'),
  ('Superband Dead Bug', 'https://youtu.be/wCwn7-Z-XjE'),
  ('Superband Good Morning', 'https://youtu.be/6U-qtYBP-bc?si=-53gPzTz2qX4pX-W'),
  ('Superband Half Kneeling Pallof Press', 'https://youtu.be/V-SoYj9uQV8'),
  ('Superband Lateral Step Hip Adduction', 'https://youtu.be/9Ryl38GZHiI'),
  ('Superband Pallof Press', 'https://youtu.be/TvPRtxN8uoA'),
  ('Superband Prone Bench Hamstring Curl', 'https://youtu.be/e5TRSsFNeug?feature=shared'),
  ('Superband Prone Hamstring Curl', 'https://youtu.be/LtTcXXgeRYo?si=80zdQRqZ21dGBf6n'),
  ('Superband Prone Single Leg Hamstring Curl', 'https://youtu.be/0spHTVOeZ-4?feature=shared'),
  ('Superband Pull Through', 'https://youtu.be/ZuKowDpVVXM'),
  ('Superband Single Leg Standing Bent Knee Hip External Rotation', 'https://youtu.be/z97Mxord2Po'),
  ('Superband Standing Hip Adduction', 'https://youtu.be/O2fzFpGvDWI'),
  ('Superband Tall Kneeling Pallof Press', 'https://youtu.be/yUzjX1LdySo?si=2LpxjTl8N8OHsKqd'),
  ('Suspension Alternating Cossack Squat', 'https://youtu.be/ThQT_AIqcNU?si=Y06NKpeBBOkHRplH'),
  ('Suspension Alternating Curtsy Lunge', 'https://youtu.be/jNjDO9lEenw?si=Ci4DITj3193GY1tI'),
  ('Suspension Alternating Lateral Lunge', 'https://youtu.be/0bqrj4BimaI?si=03pxBE_5_ozxIivb'),
  ('Suspension Alternating Reverse Lunge', 'https://youtu.be/oRO4ailwZb4'),
  ('Suspension Body Saw', 'https://youtu.be/u8BCm4GkOSY?si=mivk-6ghBacHbVR9'),
  ('Suspension Cossack Squat', 'https://youtu.be/kZdZsw22lU4?si=Y2-3ATlU1R18Acir'),
  ('Suspension Curtsy Lunge', 'https://youtu.be/tiuw2sbuhl0?si=TK4HTHPYjPWelq8-'),
  ('Suspension Cyclist Squat', 'https://youtu.be/dzbJzUQjDYA?feature=shared'),
  ('Suspension Feet Elevated Forearm Plank', 'https://youtu.be/hRWpFtDyofg?si=Xwts69VNdiYCB5-r&utm_source=MTQxZ'),
  ('Suspension Feet Elevated Glute Bridge', 'https://youtu.be/bZUGEwxZVks?si=GXDy3dTxYcWMuQpw'),
  ('Suspension Feet Elevated Plank', 'https://youtu.be/g93DurTL79E?si=BG_2IXTND6t0_DRn&utm_source=MTQxZ'),
  ('Suspension Hamstring Curl', 'https://youtu.be/xh13VO9_qEA?si=lzogbMJOWGILmMX3'),
  ('Suspension Knee Tuck', 'https://youtu.be/z2tctrNfTrY'),
  ('Suspension Low Row', 'https://youtu.be/hULU2N_9qjk?si=XmozOzBr-Uny0t4A'),
  ('Suspension Mid Row', 'https://youtu.be/W-nnq0Ks1A0'),
  ('Suspension Sissy Squat', 'https://youtu.be/YedqbteiWoU?si=rMl_RLv88kcBcMUR'),
  ('Suspension Skater Squat', 'https://youtu.be/YyBeT4WWBk4'),
  ('Suspension Split Squat', 'https://youtu.be/sng5EOSZSSo'),
  ('Suspension Squat', 'https://youtu.be/MafftY-3lC0?si=bGTlr29qg0ZvBtT_'),
  ('Tire Alternating Step Up', 'https://youtu.be/JdYIi6Vedy8?si=XLKOd1kgeuZgH3Wp'),
  ('Tire Mountain Climber', 'https://youtu.be/-ouYHaP9g9g?si=qc9f_XLeK0tBdsDc'),
  ('Tire Sledge Hammer Staggered Stance Slam', 'https://youtu.be/ykhGpORlJ4Y?si=6hFSwmMbG1lGLXki'),
  ('Tire Step Up', 'https://youtu.be/4RsPF6KynpE?feature=shared'),
  ('Trap Bar Bent Over Row', 'https://youtu.be/aNllFax4shk?si=J0w79P4ud8wpm67U'),
  ('Trap Bar Deadlift', 'https://youtu.be/FYx76NSijfU?si=SQ4p_SUWbJGUlk0N'),
  ('Trap Bar Pendlay Row', 'https://youtu.be/d5rLWfIN9fo?si=iiKqMHW4Xr9OMyaR'),
  ('Trap Bar Rack Pull', 'https://youtu.be/5zBwce39LfU?si=N9TY90hZ5tEbb3oc'),
  ('Trap Bar Romanian Deadlift', 'https://youtu.be/2L_LpH_IIbc?si=bI9uPdiltgD6G9Mf'),
  ('Trap Bar Staggered Stance Deadlift', 'https://youtu.be/UfCzhPWBmhU?si=PEQal1FTSXhdUQED'),
  ('Wall Ball Body Saw', 'https://youtu.be/Ke3i_CAVF6E?si=pJ9XGgJjXXGUnY95'),
  ('Wall Ball Feet Elevated Russian Twist', 'https://youtu.be/w0CTy_eIIcM?si=RtrXOHk6gyF6NsFi'),
  ('Wall Ball Half Kneeling Lateral Toss', 'https://youtu.be/OE8VmAtG3iw?feature=shared'),
  ('Wall Ball Lateral Toss', 'https://youtu.be/R87xzEuBmlY?si=tsszJ0gQHwdhFaFH'),
  ('Wall Ball Russian Twist', 'https://youtu.be/0DwFec0Aeog?si=bohJ8yWsahjfyyVf'),
  ('Wall Ball Russian Twist Lateral Toss', 'https://youtu.be/A7Gs9U3l_bM?si=gYbFmn76YoyxmFzn')
) as v(name, link)
where e.name = v.name
  and e.video_url like 'https://www.youtube.com/results?search_query=%';
